<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE menu [
  <!ELEMENT menu (group+)>
    <!ELEMENT group (item+)>
    <!ATTLIST group top   (Y|N) 'N'
                    title CDATA #IMPLIED>
      <!ELEMENT item EMPTY>
      <!ATTLIST item href  CDATA #REQUIRED
                     label CDATA #REQUIRED
                     param CDATA #IMPLIED>
]>

<menu>

<group top='Y'>
<item href="/main/en/about.xml"        label="About"/>
<item href="/proj/en/"                 label="Projects"/>
<item href="/doc/en/"                  label="Docs"/>
<item href="https://forums.gentoo.org/" label="Forums"/>
<item href="/main/en/lists.xml"        label="Lists"/>
<item href="http://bugs.gentoo.org/"   label="Bugs"/>
<item href="/main/en/where.xml"        label="Get Gentoo!"/>
<item href="/main/en/support.xml"      label="Support"/>
<item href="http://planet.gentoo.org/" label="Planet"/>
<item href="https://wiki.gentoo.org/"   label="Wiki"/>
</group>

<group title="Get Started">
<item href="/doc/en/handbook/"  label="Gentoo Handbook"/>
<item href="/main/en/where.xml" label="Downloads"/>
</group>

<group title="News">
<item href="/security/en/" label="Security Announcements"/>
<item href="https://www.google.com/calendar/embed?src=88di0t0pl2cfau7oak48rbccfs%40group.calendar.google.com&amp;showCalendars=0&amp;color=%235229A3" label="Calendar"/>
<item href="http://infra-status.gentoo.org/" label="Infrastructure Status"/>
</group>

<group title="Documentation">
<item href="/doc/en/handbook/" label="Gentoo Handbook"/>
<item href="https://wiki.gentoo.org/wiki/Project:Documentation/Overview"  label="Featured Documentation"/>
<item href="/doc/en/articles/" label="IBM dW/Intel article archive"/>
</group>

<group title="Get Gentoo">
<item href="/main/en/where.xml"          label="Downloads"/>
<item href="/main/en/mirrors2.xml"       label="Mirrors"/>
<!-- <item href="http://torrents.gentoo.org/" label="Torrents"/> -->
</group>

<group title="Community">
<item href="https://forums.gentoo.org/"   label="Discussion Forums"/>
<item href="/main/en/irc.xml"            label="IRC Channels"/>
<item href="/main/en/lists.xml"          label="Mailing Lists"/>
<item href="http://bugs.gentoo.org"      label="Report Issues"/>
<item href="http://planet.gentoo.org"    label="Planet (Blogs)"/>
<item href="https://packages.gentoo.org/" label="Online Package Database"/>
<item href="https://wiki.gentoo.org/"     label="Wiki"/>
<item href="/main/en/contact.xml"        label="Contact Us"/>
<item href="/main/en/sponsors.xml"       label="Sponsors"/>
</group>

<group title="Get Involved">
<item href="http://bugs.gentoo.org"          label="Report Issues"/>
<item href="/proj/en/devrel/staffing-needs/" label="Help Wanted"/>
<item href="/proj/en/qa/proxy-maintainers/"  label="Help maintaining packages"/>
<item href="https://forums.gentoo.org/"       label="Discussion Forums"/>
<item href="/main/en/irc.xml"                label="IRC Channels"/>
<item href="/main/en/lists.xml"              label="Mailing Lists"/>
<item href="/proj/en/devrel/handbook/handbook.xml"	label="Become a Developer"/>
<item href="/proj/en/userrel/adopt-a-dev/"   label="Offer Resources"/>
<item href="/proj/en/glep/"                  label="Enhancement Proposals (GLEPs)"/>
<item href="http://anoncvs.gentoo.org/"      label="Source Repositories"/>
<item href="https://devmanual.gentoo.org" label="Developer's Manual"/>
</group>

<group title="Other">
<item href="/proj/en/devrel/roll-call/userinfo.xml" label="Developer&#xA0;List"/>
<item href="/proj/en/devrel/roll-call/devmap.xml"   label="Developer&#xA0;Map"/>
<item href="/main/en/stores.xml"					label="Gentoo Stores"/>
<item href="/proj/en/"                              label="Projects"/>
</group>

<group title="About">
<item href="/main/en/about.xml"      label="About Gentoo"/>
<item href="/main/en/philosophy.xml" label="Philosophy"/>
<item href="/main/en/contract.xml"   label="Social Contract"/>
<item href="/main/en/name-logo.xml"  label="Name and Logo Guidelines"/>
<item href="/main/en/graphics.xml"   label="Logos and themes"/>
<item href="/main/en/shots.xml"      label="Screenshots"/>
</group>

</menu>
