<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="/proj/en/gdp/tests/amd64/amd64-tests.xsl" type="text/xsl"?>
<?xml-stylesheet href="/xsl/guide.xsl" type="text/xsl"?>

<!DOCTYPE amd64-tests [
<!ELEMENT amd64-tests             (test+)>
  <!ELEMENT test                  (#PCDATA)>
  <!ATTLIST test          id      CDATA #REQUIRED>
  <!ATTLIST test          dev     CDATA #REQUIRED>
  <!ATTLIST test          bug     CDATA "n/a">
  <!ATTLIST test          status  (UNTESTED | WORKED | FAILED) "UNTESTED">
]>

<amd64-tests>
  <test id="1" dev="neysx">
   What's your favourite colour?
  </test>
  <test id="2" dev="swift" status="WORKED">
   Your mother was a hamster
  </test>
  <test id="a" dev="kugelfang" status="FAILED">
   Bring me a shrubbery!
  </test>
  <test id="zz" dev="klieber" bug="77777">
   Ni!
  </test>
</amd64-tests>
