=== ulm/gentoo-historical/xml/old-web/dtd/guide.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY  % content.class	"figure|fig|img|br|note|impo|warn|i|b|brite|c|box|pre|path|uri|p|e|mail|table|ul|ol">

<!ELEMENT guide			(title, subtitle?, author+, abstract, version, date, newsitems?, chapter+)>
<!ATTLIST guide			type (project) #IMPLIED
						link CDATA #IMPLIED
						mainpage (yes|no) "no"
						mainid (news|about|contract|packages|graphics|articles|docs|changelog|projects) #IMPLIED>
<!ELEMENT newsitems		(news+)>
<!ELEMENT news			(poster, date, title, body)>
<!ATTLIST news			gentoo (yes|no) "no"
						category (gentoo|main|ibm|linux|moo|nvidia) #REQUIRED>
<!ELEMENT title			(#PCDATA)>
<!ELEMENT subtitle		(#PCDATA)>
<!ELEMENT author		(mail)>
<!ATTLIST author		title CDATA #REQUIRED>
<!ELEMENT mail			(#PCDATA)>
<!ATTLIST mail			link CDATA #REQUIRED>
<!ELEMENT abstract		(#PCDATA)>
<!ELEMENT version		(#PCDATA)>
<!ELEMENT date			(#PCDATA)>
<!ELEMENT chapter		(title, section+)>
<!ELEMENT section		(title?, body)>
<!ELEMENT body			(%content.class;)*>
<!ELEMENT figure		(EMPTY)>
<!ATTLIST figure		caption CDATA #IMPLIED
						short CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT fig			(EMPTY)>
<!ATTLIST fig			short CDATA #IMPLIED
						linkto CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT img			EMPTY>
<!ATTLIST img			src CDATA #REQUIRED>
<!ELEMENT br			(#PCDATA)>
<!ELEMENT note			(#PCDATA)>
<!ELEMENT impo			(#PCDATA)>
<!ELEMENT warn			(#PCDATA)>
<!ELEMENT codenote		(#PCDATA)>
<!ELEMENT comment		(#PCDATA)>
<!ELEMENT i				(#PCDATA)>
<!ELEMENT b				(#PCDATA)>
<!ELEMENT brite			(#PCDATA)>
<!ELEMENT c				(#PCDATA)>
<!ELEMENT box			(#PCDATA)>
<!ELEMENT pre			(#PCDATA)>
<!ATTLIST pre			caption CDATA #IMPLIED>
<!ELEMENT path			(#PCDATA)>
<!ELEMENT uri			(#PCDATA)>
<!ATTLIST uri			link CDATA #IMPLIED>
<!ELEMENT p				(#PCDATA|%content.class;)*>
<!ELEMENT e				(#PCDATA)>
<!ELEMENT table			(tr+)>
<!ELEMENT tr			(th+|ti+)>
<!ELEMENT th			(#PCDATA|%content.class;)*>
<!ELEMENT ti			(#PCDATA|%content.class;)*>
<!ELEMENT ul			(li+)>
<!ELEMENT ol			(li+)>
<!ELEMENT li			(#PCDATA|%content.class;)*>

=== ulm/gentoo-historical/xml/htdocs/doc/nl/conky-howto.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- $Id: conky-howto.xml,v 1.4 2012/06/30 18:42:54 swift Exp $ -->
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide disclaimer="obsolete" lang="nl">
<title>Gentoo Linux Conky Howto</title>

<author title="Author">
  <mail link="admin@sdesign.us">Bill Woodford</mail>
</author>
<author title="Editor">
  <mail link="brenden@rty.ca">Brenden Matthews</mail>
</author>
<author title="Vertaler">
  <mail link="jonas@belandi.be">Jonas Drieghe</mail>
</author>
<author title="Vertaler">
  <mail link="diox@gentoo.org">Dimitry Bradt</mail>
</author>

<abstract>
Dit document omschrijft hoe je de systeemmonitor Conky installeert en
configureert.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1.2</version>
<date>2006-11-02</date>

<chapter>
<title>Achtergrond</title>
<section>
<title>Inleiding op Conky</title>
<body>

<p>Je hebt eindelijk je Gentoo machine en je hebt reeds 30 verschillende
commando's geleerd om de diverse aspecten van wat je computer aan het doen is
te monitoren. Wat doe je nu?  Is er geen eenvoudigere manier om de
systeemperformance te monitoren, om te zien wat het systeem aan het doen is en
om na te gaan welke bronnen je systeem in welke mate voor deze taken gebruikt?
Jawel, die is er. Dit is wat een systeemmonitor zoals Conky voor jou kan doen.
</p>

</body>
</section>
<section>
<title>Wat het doet</title>
<body>

<p>
In tegenstelling tot andere systeemmonitoren zoals top, kan Conky draaien als
een venster in een X sessie, of door rechtstreeks te schrijven naar het root
venster (er is ook de optie om de informatie van Conky naar stdout te schrijven,
maar dat bespreken we hier niet).  Conky geeft de verzamelde informatie weer in
de vorm van text, vooruitgangsbalken en grafieken.  Daarenboven is de Conky
uitvoer volldig door de gebruiker te configureren (in tegenstelling tot top).
Naast het monitoren van het systeem zelf kan Conky ook informatie geven over
verscheidene muziekspelers (zoals BMPx, Music Player Daemon en Audacious).
Conky kan je ook vertellen hoeveel nieuwe berichten in er jouw mail spool
zitten, en nog zoveel meer.  Als de functionaliteit die jij wenst nog niet in
Conky zit, kan je heel eenvoudig zelf een script schijven om de gewenste
informatie op te halen.  Enkele reeds uitgewerkte voorbeelden hiervaan zijn RSS
feeds, POP3 e-mail berichten teller, lokaal weerbericht, boinc status en zelfs
de status van portage.
</p>

</body>
</section>
</chapter>

<chapter>
<title>Conky installeren</title>
<section>
<title>Basis installatie</title>
<body>

<p>
Gentoo voorziet een ebuild om Conky snel en eenvoudig te installeren.  Hierbij
moet je vooral aandacht hebben voor de USE flags. Hoogstwaarschijnlijk wil je
X11 ondersteuning(<c>X</c>).  Daarnaast selecteer je best ook de USE flag voor
elke mediaspeler (naast MPD) die je wil gebruiken, zoals Audacious
(<c>audacious</c>). Als je de TCP poort monitor wil gebruiken moet je zeker de
<c>ipv6</c> USE flag uitschakelen. Dit is nodig omdat de poort monitor enkel
voor ipv4 systemen werkt.
</p>

<p>
In addition, the <c>truetype</c> USE flag compiles support for TrueType fonts
with the use of Xft. Most users will want this as well.
</p>

<pre caption="/etc/portage/package.use">
<comment>(Gebruik hetvolgende als een voorbeeld)</comment>
# <i>echo app-admin/conky truetype audacious -infopipe -ipv6 >> /etc/portage/package.use</i>
</pre>

<p>
Wanneer je de correcte USE flags hebt ingesteld is het tijd om Conky te
installeren !
</p>

<pre caption="Conky Installeren">
# <i>emerge -av conky</i>
</pre>

<p>
Je kan Conky testen om te bekijken hoe het er uit zal zien door envoudig weg het
commando <c>conky</c> uit te voeren in een terminal. Dit zal je een goed beeld
geven van hoe het er uit zal zien en wat je wil veranderen, toevoegen of zelfs
verwijderen.
</p>

<pre caption="Conky voor de eerste maal starten">
$ <i>conky</i>
</pre>

<note>
Conky heeft Double Buffer Extension (DBE) ondersteuning nodig van de X server
om flikkeringen te voorkomen. Dit komt omdat Conky het wenster niet snel genoeg
kan verversen zonder DBE.  Dit kan ingeschakeld worden in
<path>/etc/X11/xorg.conf</path> met de <c>Load "dbe"</c> lijn in <b>Section
"Module"</b>.
</note>

<p>
Wanneer je een idee hebt over hoe Conky er uit ziet kan je overschakelen tot de
configuratie!
</p>

</body>
</section>
<section>
<title>Conky configureren</title>
<body>

<p>
Standaard zal Conky zoeken voor het configuratiebestand <path>~/.conkyrc</path>
in de home map van de gebruiker.  Dit bestand bevat alle configuratie opties en
de statische tekst, kleuren en andere variabelen die bepalen welke data aan de
gebruiker wordt weergegeven.  Conky voorziet ook een schitterende
voorbeeldconfiguratie in
<path>/usr/share/doc/&lt;conky-version&gt;/Conkyrc.sample.gz</path>  Vervang
&lt;conky-version&gt; door de specifieke versie van Conky die jij hebt
geïnstalleerd.
</p>

<pre caption="De voorbeeldconfiguratie kopiëren naar jouw home map">
<comment>(Vervang <b>1.4.0-r1</b> door de versienummer van Conky)</comment>
$ <i>zcat /usr/share/doc/conky-1.4.0-r1/conkyrc.sample.gz >> ~/.conkyrc</i>
</pre>

<p>
Open nu de voorbeeldconfiguratie in een textverwerker naar keuze.  Je zal
opmerken dat er twee afzonderlijke delen in het configuratiebestand zijn.  Het
eerste deel van het bestand bevat de programmaconfiguratie en bepaalt hoe Concky
zich gedraagt.  Dit bevat ondermeer opties zoals <c>update_interval</c>, wat
bepaalt hoe dikwijls Conky de informate op het scherm zal actualiseren.  Het
tweede deel bevat de effectieve tekst, grafieken en variabelen die op het scherm
zullen worden weergegeven.  Dit deel bevat onderandere dingen zoals systeem
uptime (<c>$uptime</c>), cpu gebruik (<c>$cpu</c>) en alle andere dingen die jij
op je scherm wil zien.  Het eerste deel van het bestand start aan het het begin.
Het tweede deel bestaat uit alles achter de lijn <c>TEXT</c>.  Commentaar in het
bestand start met <c>#</c>, maar hou in het achterhoofd dat wanneer een
lijn in commentaar is gezet in het tweede deel van het bestand, de tekst toch
naar het scherm zal worden geschreven.
</p>

<p>
Een lijst van alle mogelijke configuratie opties en variabelen is te vinden op
<uri>http://conky.sourceforge.net/config_settings.html</uri> en
<uri>http://conky.sourceforge.net/variables.html</uri>. Daarnaast zijn er een
aantal mooie screenshots, enkele voorbeeldconfiguraties en een aantal scripts
terug te vinden op <uri>http://conky.sourceforge.net/screenshots.html</uri>.
</p>

</body>
</section>
</chapter>

<chapter>
<title>Conky uitbreiden</title>
<section>
<title>Meer dan enkel de ingebouwde variabelen</title>
<body>

<p>
Je bent al een heel eind opgeschoten met Conky en je hebt alle documentatie
uitgepluisd op zoek naar die extra variabele die Conky blijkbaar niet bezit...
Geen paniek!  Conky voorziet enkele variabelen die exact hiervoor zijn
gecreëerd.  <c>$exec</c> Zal een commando uitvoeren telkens wanneer Conky
actualiseert, <c>$execi</c> zal een commando uitvoeren op een gekozen interval
en <c>$texeci</c> zal een commando uitvoeren in zijn eigen thread op een gekozen
interval.
</p>

<pre caption="Script voorbeelden">
<i>${exec grep 'sudo' /var/log/messages | tail -n 4}</i>
<i>${execi 30 ~/scripts/emerge-status.sh</i>
<i>${texeci 600 ~/scripts/gmail.pl}</i>
</pre>

<note>
Hoewel elk commando dat in een shell werkt ook in elk van deze variabelen werkt
is het belangrijk om te onthouden dat het commando MOET eindigen. Dit wil
zeggen dat commando's zoals <c>tail -f</c> die blijven draaien <e>niet</e>
correct functionneren.
</note>

</body>
</section>
</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/proj/en/perl/outdated-cpan-packages-perl-experimental.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/en/perl/outdated-cpan-packages-perl-experimental.xml,v 1.859 2012/08/15 13:58:30 tove Exp $ -->

<!-- Do Not Translate !! -->
<guide link="/proj/en/perl/outdated-cpan-packages-perl-experimental.xml">
<title>Outdated CPAN Packages (perl-experimental vs CPAN)</title>

<author title="Author">
  Script generated using up2date-ng version 0.24
</author>

<abstract>
  This document lists the packages suspected as outdated
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1.0</version>
<date>2012-08-15</date>

<chapter>
<title>Intro</title>
<section>
<body>

<p>
This list is not exhaustive and may contain mistakes/errors. Accuracy is only
guaranteed at 90% and is generated to inform developers about which CPAN
modules are currently out of date in perl-experimental. Our most frequent bug request is
for module bumping. This list is intended as acknowledgement (and hopefully
will curb some of the bugs to boot).
</p>

</body>
</section>
</chapter>

<chapter>
<title>List of outdated packages</title>
<section>
<body>

<table>
  <tr>
    <th>Packagename</th>
    <th>Version in perl-experimental</th>
    <th>Version on CPAN</th>
    <th>Diff</th>
  </tr>
    <tr>
    <ti><uri link="http://metacpan.org/release/Gentoo-Perl-Distmap">Gentoo-Perl-Distmap</uri></ti>
    <ti align="right">0.1.2</ti>
    <ti align="right"><uri link="http://metacpan.org/release/KENTNL/Gentoo-Perl-Distmap-0.1.3/">0.1.3</uri></ti>
    <ti><uri link="http://metacpan.org/diff/release/KENTNL/Gentoo-Perl-Distmap-0.1.2/KENTNL/Gentoo-Perl-Distmap-0.1.3">Diff</uri></ti>
  </tr>
  <tr>
    <ti><uri link="http://metacpan.org/release/Imager">Imager</uri></ti>
    <ti align="right">0.910.0</ti>
    <ti align="right"><uri link="http://metacpan.org/release/TONYC/Imager-0.92/">0.92</uri></ti>
    <ti><uri link="http://metacpan.org/diff/release/TONYC/Imager-0.91/TONYC/Imager-0.92">Diff</uri></ti>
  </tr>
  <tr>
    <ti><uri link="http://metacpan.org/release/Mojolicious">Mojolicious</uri></ti>
    <ti align="right">3.280.0</ti>
    <ti align="right"><uri link="http://metacpan.org/release/SRI/Mojolicious-3.31/">3.31</uri></ti>
    <ti><uri link="http://metacpan.org/diff/release/SRI/Mojolicious-3.28/SRI/Mojolicious-3.31">Diff</uri></ti>
  </tr>
  <tr>
    <ti><uri link="http://metacpan.org/release/POE-Component-Resolver">POE-Component-Resolver</uri></ti>
    <ti align="right">0.920.0</ti>
    <ti align="right"><uri link="http://metacpan.org/release/RCAPUTO/POE-Component-Resolver-0.921/">0.921</uri></ti>
    <ti><uri link="http://metacpan.org/diff/release/RCAPUTO/POE-Component-Resolver-0.920/RCAPUTO/POE-Component-Resolver-0.921">Diff</uri></ti>
  </tr>
</table>

<p>
Total packages suspected as outdated: 4 of 797
</p>

</body>
</section>
</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/doc/nl/java.xml
<?xml version='1.0' encoding="UTF-8"?>

<!-- $Id: java.xml,v 1.7 2012/06/30 18:42:54 swift Exp $ -->

<!-- Rev 1.7 -->

<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<guide disclaimer="obsolete" link = "/doc/nl/java.xml">
<title>Gentoo Java Handleiding</title>
<author title="Author and Editor">
    <mail link="karltk@gentoo.org">Karl Trygve Kalleberg</mail>
</author>
<author title="Translator">
    <mail link="swift@gentoo.org">Sven Vermeulen</mail>
</author>
<author title="Translator">
	<mail link="blubber@gentoo.org">Tiemo Kieft</mail>
</author>


<abstract>
Gebruikers- en ontwikkelaarshandleiding tot Java onder Gentoo
</abstract>

<license/>
<version>0.1.2</version>
<date>4 September 2003</date>

<chapter>
<title>Een JDK/JRE installeren</title>
<section>
<title>Overzicht</title>
<body>

<p>
Gentoo levert verschillende JDKs en JREs. De default is de
blackdown JDK/JRE set, en is vrij beschikbaar zonder eender welke
registratiemoeilijkheden.
</p>

<note>
Aangezien kaffe hun JRE/JDK steeds verder en verder ontwikkelt zal
deze waarschijnlijk onze toekomstige set worden.
</note>


<p>
Zowel de Sun JDK/JRE als de IBM JDK/JRE zijn in het algemeen
sneller, maar om hen werkende te krijgen is er iets meer werk
vereist, aangezien je hun licentie moet lezen alvorens je die kan
downloaden (en die van IBM vereist tevens dat je je registreert).
</p>

<p>
Onze ebuilds voor de Sun en IBM JDK/JRE's zullen je uitleggen waar
je deze kan downloaden.
</p>

</body>
</section>

<section>
<title>De Sun/IBM JDK/JREs installeren</title>
<body>

<p>
Indien je <c>emerge sun-jdk-1.3.1</c> of <c>emerge
ibm-jdk-1.3.1</c> uitvoert zal je verteld worden dat je de nodige
bestanden manueel moet downloaden. Dit heeft met licenties te
maken (de Sun JDK/JRE online click-wrap licentie of de IBM JDK/JRE
registratie).
</p>

<note>
Er is tevens een sun-jdk-1.4.0, maar niet alle packages werken goed
met Java 1.4, dus indien je werkelijk 1.4 wenst is er een kans dat je later 
zal sukkelen.
</note>

<p>
Je moet de bestanden downloaden en in <path>/usr/portage/distfiles</path> 
plaatsen. Eenmaal dat gebeurd is kan je het emerge commando opnieuw uitvoeren 
opdat de JDK/JRE goed geinstalleerd zou worden in <path>/opt</path>.
</p>

</body>
</section>
</chapter>

<chapter>
<title>De JDK/JRE configureren</title>

<section>
<title>Overzicht</title>

<body>

<p>
Gentoo heeft de mogelijkheid om meerdere JDKs en JREs geinstalleerd
te staan hebben zonder dat ze in elkaars vaarwater komen. Er zijn
enkele zaken die je moet doen om dit succesvol ten einde te
brengen, zoals later vermeld wordt.
</p>

<p>
Door gebruik te maken van de <c>java-config</c> tool kan je de
systeem-defaults instellen (indien je root-access hebt tenminste).
Gebruikers kunnen ook hiervan gebruik maken, maar dit is dan enkel
voor hun eigen instellingen (uiteraard).
</p>

</body>
</section>

<section>
<title>Een default JDK/JRE instellen</title>
<body>

<p>
Het commando <c>java-config --list-available-vms</c> zal je een
lijst geven met beschikbare JREs en JDKs op je systeem:
</p>

<pre caption = "Beschikbare VMs voorbeeld">
~# java-config --list-available-vms
[blackdown-jdk-1.3.1] Blackdown JDK 1.3.1 (/etc/env.d/java/20blackdown-jdk-1.3.1)
[blackdown-jre-1.3.1] Blackdown JRE 1.3.1 (/etc/env.d/java/20blackdown-jre-1.3.1)
[ibm-jdk-1.3.0] IBM JDK 1.3.0 (/etc/env.d/java/20ibm-jdk-1.3.0)
[ibm-jdk-1.3.1] IBM JDK 1.3.1 (/etc/env.d/java/20ibm-jdk-1.3.1)
[ibm-jre-1.3.1] IBM JRE 1.3.1 (/etc/env.d/java/20ibm-jre-1.3.1)
[sun-jdk-1.4.0] Sun JDK 1.4.0 (/etc/env.d/java/20sun-jdk-1.4.0)
</pre>

<p>
De namen tussen de haakjes <path>&quot;[]&quot;</path> zijn de namen
of IDs van die specifieke VMs. Je kan een van deze IDs doorgeven aan
<c>java-config --set-system-vm</c>:
</p>

<pre caption = "Het Java VM systeem instellen">
~# java-config --set-system-vm=ibm-jdk-1.3.1
Now using IBM JDK 1.3.1 (/etc/env.d/java/20ibm-jdk-1.3.1)
</pre>

<note>
Je moet root-access hebben om --set-system-vm uit te kunnen voeren.
</note>

<p>
Nadat je een specifieke vm meegegeven hebt aan <c>java-config
--set-system-vm</c> dan moet je je <path>/etc/profile.env</path>
regenereren:
</p>

<pre caption = "/etc/profile.env regenereren" >
~# env-update
</pre>

<p>
Hierna moet je ofwel herinloggen op je systeem, of
<path>/etc/profile</path> sourcen in je huidige shell.
</p>

<p>
Als gewone gebruiker kan je <c>java-config --set-user-vm</c>
uitvoeren, wat een <path>$HOME/.gentoo/java-env</path> zal aanmaken
met daarin alle nodige omgevingsvariabelen. Je zou dit bestand het
best sourcen vanuit je <path>~/.profile</path>.
</p>

</body>
</section>

<section>
<title>Een CLASSPATH instellen</title>
<body>

<p>
<c>java-config</c> kan gebruikt worden om een systeemwijde of 
gebruiker-afhankelijke CLASSPATH in te stellen (afhankelijk of je als root of
als niet-gepriviligeerde gebruiker werkt).
</p>

<p>
Allereerst zal je een lijst willen aanmaken met java bibliotheken
die je in je CLASSPATH wil steken:
</p>

<pre caption = "Classes weergeven">
~$ java-config --list-available-packages
[ant] No description (/usr/share/ant/classpath.env)
[java-gnome] No description (/usr/share/java-gnome/classpath.env)
[java-gtk] No description (/usr/share/java-gtk/classpath.env)
[log4j] &quot;&quot; (/usr/share/log4j/package.env)
</pre>

<note>
Geen enkel van deze packages hebben een duidelijke omschrijving.
Dat is iets wat in de niet-zoverre toekomst geimplementeerd zal
worden.
</note>

<p>
Opnieuw, de namen tussen de haakjes zijn de IDs die je aan
<c>java-config --set-system-classpath</c> kan doorgeven:
</p>

<pre caption = "Classpaths instellen">
~# java-config --set-system-classpath=log4j,java-gtk,java-gnome
</pre>

<note>
De huidige directorie mag <e>niet</e> deel zijn van de classpath,
aangezien dat gebruikersafhankelijk moet zijn!
</note>

<p>
Opnieuw zal je moeten <c>env-update</c> moeten uitvoeren om je
omgevingsvariabelen algemeen in orde te zetten, en zal je opnieuw
moeten inloggen of <path>/etc/profile</path> sourcen.
</p>

<p>
Voor gebruikers zal <c>java-config --set-user-classpath</c>
<path>~/.gentoo/java-env-classpath</path> aanmaken die door
<path>~/.gentoo/java-env</path> vanzelf gesourced wordt.
</p>

</body>
</section>
</chapter>

<chapter>
<title>Extra resources</title>
<section>
<title>Off-line resources</title>

<body>

<ul>
<li>java-config man page</li>
<li><c>java-config --help</c></li>
<li>Het <path>/usr/bin/java-config</path> script zelf</li>
</ul>

</body>
</section>

<section>
<title>Online resources</title>

<body>

<ul>
<li>De <uri link="http://news.gmane.org/gmane.linux.gentoo.devel">gentoo-dev</uri>, 
 <uri link="http://news.gmane.org/gmane.linux.gentoo.user">gentoo-user</uri> 
 mailing list archieven</li>
<li>#gentoo op irc.freenode.net</li>
</ul>

</body>
</section>
</chapter>

<chapter>
<title>Addertjes</title>
<section>
<title>Algemene</title>

<body>

<p>
Indien je een JRE als default VM aanduidt kan het zijn dat je geen
<c>javac</c> commando beschikbaar meer hebt, tenzij je manueel een
symlink aanmaakt om dit probleem op te lossen.
</p>

<p>
Jikes zal gebruikt worden om de grotere packages te compileren
indien het beschikbaar is. In tijd zullen we proberen om alle
java-afhankelijke packages met Jikes te compileren zodat sommige
afhankelijkheden van de JDK naar afhankelijkheden naar de JRE
kunnen overgezet worden.
</p>

<p>
Met nieuwere versies van Portage zal <c>emerge --update world</c>
de JDK installeren onafhankelijk van het feit of je die voordien
geinstalleerd hebt of niet. Dit is een bekende fout die in latere
versies van Portage zal geelimineerd worden.
</p>

</body>
</section>
</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/proj/it/desktop/artwork/colors.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide lang="it" disclaimer="draft">
<title>Tavolozza dei colori di Gentoo</title>

<author title="Author">
  <mail>sping</mail>
</author>
<author title="Traduzione">
  <mail link="hujuice@inservibile.org">Sergio Vaccaro</mail>
</author>

<abstract>
Informazioni sui colori usati in Gentoo.
</abstract>

<license />


<version>3</version>
<date>2011-06-03</date>


<chapter>
<title>A proposito di questo documento</title>

<section>
<body>

<p>
Questa pagina è stata pensata per facilitare la selezione dei colori alle
persone che si dedicano ai lavori artistici per Gentoo.
</p>

<note>
I colori elencati in questa pagina solo prelevati da <uri
link="/css/main.css">main.css</uri> e <uri link="/xsl/guide.xsl">guide.xsl</uri>
e poi suddivisi in categorie.<br />
Se un colore è stato posto nella categoria sbagliata, contattare il <mail
link="artwork">Gentoo Artwork Team</mail>.
</note>

<impo>
Per favore, non cancellate i colori da questa pagina a meno che non siano stati
eliminati sia da <uri link="/css/main.css">main.css</uri> e sia da <uri
link="/xsl/guide.xsl">guide.xsl</uri>.
</impo>

</body>
</section>
</chapter>


<chapter>
<title>Principali colori Gentoo per il web</title>

<section>
<body>

<table>
<tr>
<ti><fig link="/images/colors/color-45347bff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-7a5adaff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-a0a0f0ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-dddaecff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-ddddffff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-00ff00ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-000000ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-ffffffff-50x50.png" /></ti>
</tr>
<tr>
<th>#45347B</th>
<th>#7A5ADA</th>
<th>#A0A0F0</th>
<th>#DDDAEC</th>
<th>#DDDDFF</th>
<th>#00FF00</th>
<th>#000000</th>
<th>#FFFFFF</th>
</tr>
<tr>
<ti><fig link="/images/colors/color-bbffbbff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-ffffbbff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-ffbbbbff-50x50.png" /></ti>
</tr><tr>
<th>#BBFFBB</th>
<th>#FFFFBB</th>
<th>#FFBBBB</th>
</tr>
</table>

</body>
</section>
</chapter>


<chapter>
<title>Altri colori Gentoo</title>


<section>
<title>Blu</title>
<body>

<table>
<tr>
<ti><fig link="/images/colors/color-0000c8ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-0000ffff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-4040f0ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-5a3abaff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-5a3acaff-50x50.png" /></ti>
</tr><tr>
<th>#0000C8</th>
<th>#0000FF</th>
<th>#4040F0</th>
<th>#5A3ABA</th>
<th>#5A3ACA</th>
</tr>
<tr>
<ti><fig link="/images/colors/color-404080ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-52188cff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-320f61ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-301060ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-eeeeffff-50x50.png" /></ti>
</tr><tr>
<th>#404080</th>
<th>#52188C</th>
<th>#320F61</th>
<th>#301060</th>
<th>#EEEEFF</th>
</tr>
</table>

</body>
</section>


<section>
<title>Verdi</title>
<body>

<table>
<tr>
<ti><fig link="/images/colors/color-40ff00ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-00dd00ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-0c680cff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-236374ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-209090ff-50x50.png" /></ti>
</tr><tr>
<th>#40FF00</th>
<th>#00DD00</th>
<th>#0C680C</th>
<th>#236374</th>
<th>#209090</th>
</tr>
</table>

</body>
</section>


<section>
<title>Rossi</title>
<body>

<table>
<tr>
<ti><fig link="/images/colors/color-ff0000ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-d80000ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-c02020ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-982424ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-a06060ff-50x50.png" /></ti>
</tr><tr>
<th>#FF0000</th>
<th>#D80000</th>
<th>#C02020</th>
<th>#982424</th>
<th>#A06060</th>
</tr>
</table>

</body>
</section>


<section>
<title>Grigi</title>
<body>

<table>
<tr>
<ti><fig link="/images/colors/color-404040ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-666666ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-888888ff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-aaaaaaff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-c0c0c0ff-50x50.png" /></ti>
</tr><tr>
<th>#404040</th>
<th>#666666</th>
<th>#888888</th>
<th>#AAAAAA</th>
<th>#C0C0C0</th>
</tr>
</table>

</body>
</section>


<section>
<title>Colori vari</title>
<body>

<table>
<tr>
<ti><fig link="/images/colors/color-5f4e4eff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-a7f3feff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-b89b1cff-50x50.png" /></ti>
<ti><fig link="/images/colors/color-f000f0ff-50x50.png" /></ti>
</tr><tr>
<th>#5F4E4E</th>
<th>#A7F3FE</th>
<th>#B89B1C</th>
<th>#F000F0</th>
</tr>
</table>

</body>
</section>

</chapter>


</guide>

=== ulm/gentoo-historical/xml/htdocs/news/20070115-gwn.xml
<?xml version='1.0'?>

<!DOCTYPE news SYSTEM "/dtd/guide.dtd">

<news gentoo="yes" category="linux">

<!-- Enter your name here -->
<poster>Chris Gianelloni</poster>

<!-- Date to be displayed - usually the GWN release date -->
<date>2007-01-15</date>

<!-- Title of the news item - don't forget to change the date -->
<title>Gentoo Weekly Newsletter -- 15 January 2007</title>
<body>

<!-- Alter to your own likings -->
<p>
<b>Gentoo is looking for a new kernel maintainer for the 2.4 branch of
gentoo-sources, the Simplified Chinese translation team is seeking help, and
get information about getting your Gentoo learn on at MIT and more in
this week's <uri link="/news/en/gwn/20070115-newsletter.xml">Gentoo Weekly
Newsletter</uri>.</b> Also in this week's GWN is the usual security, bugs, and
package updates and summaries from the forums and planet.
</p>

</body>
</news>
