=== ulm/gentoo-historical/xml/old-web/dtd/guide.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY  % content.class	"figure|fig|img|br|note|impo|warn|i|b|brite|c|box|pre|path|uri|p|e|mail|table|ul|ol">

<!ELEMENT guide			(title, subtitle?, author+, abstract, version, date, newsitems?, chapter+)>
<!ATTLIST guide			type (project) #IMPLIED
						link CDATA #IMPLIED
						mainpage (yes|no) "no"
						mainid (news|about|contract|packages|graphics|articles|docs|changelog|projects) #IMPLIED>
<!ELEMENT newsitems		(news+)>
<!ELEMENT news			(poster, date, title, body)>
<!ATTLIST news			gentoo (yes|no) "no"
						category (gentoo|main|ibm|linux|moo|nvidia) #REQUIRED>
<!ELEMENT title			(#PCDATA)>
<!ELEMENT subtitle		(#PCDATA)>
<!ELEMENT author		(mail)>
<!ATTLIST author		title CDATA #REQUIRED>
<!ELEMENT mail			(#PCDATA)>
<!ATTLIST mail			link CDATA #REQUIRED>
<!ELEMENT abstract		(#PCDATA)>
<!ELEMENT version		(#PCDATA)>
<!ELEMENT date			(#PCDATA)>
<!ELEMENT chapter		(title, section+)>
<!ELEMENT section		(title?, body)>
<!ELEMENT body			(%content.class;)*>
<!ELEMENT figure		(EMPTY)>
<!ATTLIST figure		caption CDATA #IMPLIED
						short CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT fig			(EMPTY)>
<!ATTLIST fig			short CDATA #IMPLIED
						linkto CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT img			EMPTY>
<!ATTLIST img			src CDATA #REQUIRED>
<!ELEMENT br			(#PCDATA)>
<!ELEMENT note			(#PCDATA)>
<!ELEMENT impo			(#PCDATA)>
<!ELEMENT warn			(#PCDATA)>
<!ELEMENT codenote		(#PCDATA)>
<!ELEMENT comment		(#PCDATA)>
<!ELEMENT i				(#PCDATA)>
<!ELEMENT b				(#PCDATA)>
<!ELEMENT brite			(#PCDATA)>
<!ELEMENT c				(#PCDATA)>
<!ELEMENT box			(#PCDATA)>
<!ELEMENT pre			(#PCDATA)>
<!ATTLIST pre			caption CDATA #IMPLIED>
<!ELEMENT path			(#PCDATA)>
<!ELEMENT uri			(#PCDATA)>
<!ATTLIST uri			link CDATA #IMPLIED>
<!ELEMENT p				(#PCDATA|%content.class;)*>
<!ELEMENT e				(#PCDATA)>
<!ELEMENT table			(tr+)>
<!ELEMENT tr			(th+|ti+)>
<!ELEMENT th			(#PCDATA|%content.class;)*>
<!ELEMENT ti			(#PCDATA|%content.class;)*>
<!ELEMENT ul			(li+)>
<!ELEMENT ol			(li+)>
<!ELEMENT li			(#PCDATA|%content.class;)*>

=== ulm/gentoo-historical/xml/htdocs/proj/ro/releng/catalyst/faq.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="/xsl/guide.xsl" type="text/xsl"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<guide link="/proj/ro/releng/catalyst/faq.xml" lang="ro">

<title>Întrebări Frecvente despre Catalyst</title>
<author title="Autor">John Davis</author>
<author title="Autor">Daniel Robbins</author>
<author title="Contribuitor">William Kilian</author>
<author title="Editor">Chris Gianelloni</author>
<author title="Translator">
  <mail link="robert.datcu@gentoo.ro">Robert Datcu</mail>
</author>

<abstract>
Întrebări frecvente despre Catalyst.
</abstract>

<version>1.0</version>
<date>3 October 2004</date>

<chapter>
<title>Întrebări frecvente</title>

<section>
<title>Întrebări Frecvente despre Catalyst</title>
<body>

<p>
<b>Î: Cum construiesc arhive stage2 şi stage3 pentru un tip de procesor care nu
este "generic", cum ar fi <c>pentium4</c> sau <c>g4</c>?</b>
</p>

<p>
R: În primul rând, asiguraţi-vă că sistemul dvs. hardware dvs. este capabil în
a construi un astfel de fişier stage. Dacă doriţi să creaţi un fişier stage
<c>pentium4</c>, va trebui să îl construiţi pe un sistem Pentium 4 sau
AMD64/Opteron. Nu puteţi construi un fişier stage <c>pentium4</c> pe un sistem
Athlon XP, întrucât procesorul Athlon XP nu suportă instrucţiunile SSE2, iar
aceste instrucţiuni SSE2 vor fi activate pentru fişierele stages
<c>pentium4</c>. Asemănător, dacă doriţi să construiţi un fişier stage
<c>g4</c>, va trebui să faceţi aceasta pe un sistem PowerPC G4 sau G5.
</p>

<p>
Odată ce v-aţi asigurat că veţi construi pe baza hardware corectă, doar urmaţi
paşii de mai jos, dar pentru construirea unui fişier stage2, schimbaţi
variabila <c>subarch</c> cu o arhitectură non-generică validă (ex.
<c>pentium4</c>.) Apoi fişierul stage2 al dvs. va fi construit pentru
subarhitectura pe care o veţi specifica. Apoi, folosiţi acest fişier stage2 ca
stage "sursă" pentru construirea fişierului dvs. stage3. Desigur, veţi dori de
asemenea să modificaţi variabila <c>subarch</c> în specificaţiile fişierului
dvs. stage3 pentru a se potrivi cu specificaţiile fişierului dvs. stage2.
</p>

<p>
<b>Î: Vreau să construiesc mai multe fişiere stage pentru subarhitecturi
diferite. Cum ar trebui	să fac asta?</b>
</p>

<p>
R: În primul rând, construiţi un fişier stage1 generic. Apoi folosiţi acest
fişier pentru a construi fişiere specifice stage2 şi stage3. Folosiţi din nou
acest fişier stage1 pentru a construi alte fişiere specifice stage2 şi stage3.
Nu trebuie să reconstruiţi fişierul stage1 -- toate fişierele dvs. specifice
stage2 şi stage3 pot folosi acelaşi fişier "sursă" stage1.
</p>

<p>
<b>Î: Pot construi un fişier stage1 pentru un tip de CPU negeneric?</b>
</p>

<p>
R: Aceasta nu este o idee foarte bună, întrucât utilizatorii se aşteaptă ca
fişierul stage1 să funcţioneze pe orice tip de sub-arhitectură. În acest fel,
ei pot folosi fişierul stage1 pe orice sistem fără griji. Trebuie să vă
asiguraţi să nu "poluaţi" fişierul dvs. stage1 cu cod specific unui procesor
negeneric. 
</p>

<p>
<b>Î: Credeam că catalyst are posibilitatea de a construi fişiere stage
"pornind de la zero". Dacă catalyst construieşte fişiere stage "de la zero", de
ce mai este nevoie de un stage "sursă"?</b>
</p>

<p>
R: Bună întrebare. Aşa cum ştiţi, fişierele stage2 şi stage3 depind pentru
construire de fişierele stage anterioare, care sunt necesare şi identificabile
prin numele lor (de ex. "stage2" înseamnă că a existat un "stage1".) Totuşi,
catalyst are nevoie de un fişier stage de bază pentru construirea unui fişier
stage1, deci pentru a-l construi merită studiat pentru a vedea de ce este
necesar. Când construieşte un fişier stage1, catalyst foloseşte fişierul stage
bază (stage2 sau stage3) pentru a configura mediul chroot. În mediul chroot,
noul fişier stage1 este construit prin stabilirea variabilei de mediu
<c>ROOT</c> în <path>/tmp/stage1root</path>. <path>/tmp/stage1root</path> este
apoi pregătit şi devine fişierul stage1 ţintă. Ce înseamnă acestea este că
atunci când catalyst construieşte un fişier stage1, fişierul însuşi nu
moşteneşte vreun binar sau librărie din fişierulul stage de bază folosit.
Fişierul bază folosit <e>influenţează</e> cumva fişierul ţintă stage1 --
header-ele Linux din fişierul de bază sunt folosite pentru a construi pachetul
glibc al stage1, iar compilatoarele din fişierul sursă sunt folosite pentru a
compila toate programele din fişierul ţintă stage1. Fişierul stage de bază este
folosit pentru a izola procesul de construire al stage1 de sistemul dvs., şi de
asemenea permite tuturor fişierelor stage1 x86 să poată fi construite pe
sisteme amd64, de exemplu.
</p>

<p>
<b>Î: Există un ghid oficial pentru Catalyst?</b>
</p>

<p>
În acest moment, nu există un ghid oficial. Dacă sunteţi interesat în a scrie
unul, raportaţi un bug cu ghidul ataşat la acesta. Lipsa unui ghid
oficial nu înseamnă că Catalyst este complet nedocumentat. Dacă Catalyst este
instalat cu indicatorul USE <c>doc</c> activat, exemple bine comentate de
fişiere specificaţii sunt instalate în to
<path>/usr/share/doc/catalyst-$versiune/examples</path>.
</p>

<p>
Dacă încă aveţi întrebări după ce aţi citit aceste exemple, subscrieţi la lista
de mail-uri gentoo-catalyst.
</p>

<p>
<b>Î: Unde put indicatorii USE specifici fiecărui pachet, setările privind
pachetele mascate etc.?</b>
</p>

<p>
Catalyst suportă fişierele de configurare din /etc/portage. Doar adăugaţi linia
următoare în fişierul dvs. spec, şi asiguraţi-vă că folosiţi aceeaşi locaţie
<c>portage_confdir</c> pentru fişierele stage sursă, după cum urmează:  
</p>

<p>
portage_confdir: /cale/către/propriul/etc/portage
</p>

<p>
<b>Î: Chiar ar trebui să construiesc propriul stage1 sau să folosesc unul de pe
un mirror Gentoo?</b>
</p>

<p>
Fişierele stage de pe ultimul release Gentoo ar fi suficiente, doar dacă nu
plănuiţi o instalare hardened sau doriţi să schimbaţi setările profilului (de
ex. USE flags, CFLAGS, etc).
</p>

<p>
<b>Î: Cum îmi ţin actualizate pachetele mele GRP/stage/LiveCD?</b>
</p>

<p>
Catalyst foloseşte Portage pentru toate compilările, deci tot ce trebuie să
faceţi este să vă regeneraţi Portage ca snapshot şi să reconstruiţi propriile
GRP/stages/LiveCD. Portage va urma în mod normal toate regulile proprii pentru
a decide ce pachete trebuie actualizate.
</p>

<p>
<b>Î: Foloseşte Catalyst vreo sintaxă specială pentru indicatorii USE?</b>
</p>

<p>
Nu, sintaxa indicatorilor USE folosită de Catalyst este exact la fel cu cea a
Portage.
</p>

</body>
</section>

</chapter>

</guide>

=== ulm/gentoo-historical/xml/htdocs/news/20060501-gwn.xml
<?xml version='1.0'?>

<!DOCTYPE news SYSTEM "/dtd/guide.dtd">

<news gentoo="yes" category="linux">

<!-- Enter your name here -->
<poster>Ulrich Plate</poster>

<!-- Date to be displayed - usually the GWN release date -->
<date>2006-05-01</date>

<!-- Title of the news item - don't forget to change the date -->
<title>Gentoo Weekly Newsletter -- 1 May 2006</title>
<body>

<!-- Alter to your own likings -->
<p>
<b>Gentoo is going to participate as one of the mentoring organisations
in Google's "Summer of Code" event, reports today's <uri link="/news/en/gwn/20060501-newsletter.xml">Gentoo
Weekly Newsletter</uri>. A new piece of documentation now explains how to
create meaningful debugging backtraces, and the qmail herd has started 
incorporating changes suggested by users into their brandnew ebuilds.</b> 
News from the developer mailing list include an explanation for some strange
digest errors, and press clippings, GLSAs and the bugzilla statistics conclude
this week's issue of the GWN. Have fun reading it!
</p>

</body>
</news>

=== ulm/gentoo-historical/xml/htdocs/news/ru/20061002-gwn.xml
<?xml version='1.0'?>

<!DOCTYPE news SYSTEM "/dtd/guide.dtd">

<news gentoo="yes" category="linux">

<!-- Enter your name here -->
<poster>Chris Gianelloni</poster>

<!-- Date to be displayed - usually the GWN release date -->
<date>2006-10-02</date>

<!-- Title of the news item - don't forget to change the date -->
<title>Еженедельник Gentoo &mdash; 2 октября 2006</title>
<body>

<!-- Alter to your own likings -->
<p>
<b>В магазине Gentoo появились диски 2006.1. Openoffice.org проводит конкурс
шаблонов и картинок. Рассказ с LinuxParty.dk в Дании. Эти и другие новости
&mdash; в очередном номере 
<uri link="/news/ru/gwn/20061002-newsletter.xml">еженедельника
Gentoo</uri>.</b> Также в номере: советы, как &laquo;обновить мир&raquo;
(update world), не переживая о досадных сбоях пакетов.
</p>

</body>
</news>

=== ulm/gentoo-historical/xml/htdocs/proj/es/desktop/gnome/howtos/gnome-2.12-upgrade.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/es/desktop/gnome/howtos/gnome-2.12-upgrade.xml,v 1.3 2012/04/26 20:39:54 nimiux Exp $ -->

<guide link="/proj/es/desktop/gnome/howtos/gnome-2.12-upgrade.xml" lang="es">

<title>Guía de actualización a Gnome 2.12</title>

<author title="Autor">
  <mail link="allanonjl@gentoo.org">John N. Laliberte</mail>
</author>
<author title="Traductor">
  <mail link="chiguire@gentoo.org">John Christian Stoddart</mail>
</author>

<abstract>
Esta guía detalla la manera recomendada de actualizar su escritorio
Gnome a la versión 2.12. Asume que Gnome 2.12 todavía aparece como
inestable y ya no aparece en package.mask.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1.2</version>
<date>2005-10-08</date>

<chapter>
<title>¿Qué hay de nuevo? (en lo que respecta Gentoo)?</title>
<section>
<body>

<p>
¿Qué ha cambiado desde la versión 2.12_rc1?
</p>

<ul>
<li>
totem y librsvg usan gecko-sdk con el parámetro USE 'nsplugin'.
</li>
<li>evolution-exchange ya no se incluye en el metapaquete gnome.
</li>
<li>han quitado el parámetro USE firefox de evolution por
problemas con SSL (será agregado de nuevo luego).
</li>
</ul>

<p>
¿Qué ha cambiado desde 2.10.2?
</p>

<ul>
<li>mozilla ya no es un prerequisito para Gnome, ya que epiphany
puede compilar usando firefox</li>
<li>agregado el parámetro USE local 'firefox' para totem</li>
</ul>
</body>
</section>
</chapter>
  
<chapter>
<title>Preparándonos</title>
<section>
<title>Desenmascarando los paquetes</title>
<body>

<p>
Primero, empecemos por agregar los paquetes necesarios a nuestro
archivo <path>package.unmask</path>. Esto no hará falta si ya estamos
corriendo Gentoo inestable.
</p>

<note>
Una lista casi completa de paquetes que deben agregarse se puede
localizar en <uri link="http://dev.gentoo.org/~allanonjl/gnome/2.12.0/package.keywords">package.keywords.
</uri>
</note>
</body>
</section>

<section>
<title>Actualizando Python</title>
<body>

<p>
El siguiente paso es actualizar python a la versión 2.4.
</p>

<pre caption="Actualizando python">
# <i>emerge -av python</i>
# <i>python-updater</i>
</pre>
</body>
</section>

<section>
<title>Algunas otras cosas para revisar</title>
<body>

<warn>
Si ha instalado gnome-doc-utils, vuelva a hacerlo con emerge. (Ahora
debería tener una versión >= a la 0.4.1).
</warn>
</body>
</section>

<section>
<body>
<impo>¿Quiere montar automáticamente los pendrive USB y que todo lo
demás sencillamente funcione? Vea la sección "¿Y ahora qué? más adelante
en esta misma guía.
</impo>
</body>
</section>
</chapter>

<chapter>
<title>Actualizando a 2.12</title>
<section>
<body>

<p>
Esta es la parte divertida :) actualizando a Gnome 2.12.
</p>

<pre caption="Actualizando a Gnome 2.12">
# <i>emerge -av gnome</i>
</pre>

<p>
O, si quiere que no sea tan pesada la descarga:
</p>

<pre caption="Actualizando Gnome 2.12, versión ligera">
# <i>emerge -av gnome-light</i>
</pre>
</body>
</section>
</chapter>

<chapter>
<title>Correr revdep-rebuild</title>
<section>
<body>

<p>
Revise si es necesario ejecutar revdep-rebuild:
</p>

<pre caption="Corriendo revdep-rebuild">
# <i>revdep-rebuild -p</i>
</pre>

<p>
Hará falta ejecutarlo si se listan paquetes. Para correr
revdep-rebuild, hágalo sin el parámetro "-p".
</p>
</body>
</section>
</chapter>

<chapter>
<title>¿Y ahora qué?</title>
<section>
<body>

<p>
Salga de su sesión Gnome actual y ¡re-iníciela!
</p>
</body>
</section>

<section>
<title>¿Desea que los periféricos se monten automáticamente al enchufarlos?</title>
<body>

<p>
Primero, agregue hal y dbus a los parámetros USE, modificando el
<path>/etc/make.conf</path>.
</p>

<p>
Luego, asegúrese de haber desenmascarado hal, dbus, pmount y gamin (si
corre ~x86, ¡esto no es necesario!). Para usar gamin, el núcleo debe
tener activado el inotify.
</p>

<p>
La opción inotify está localizada en "File systems -> Inotify file change notification support".
</p>

<pre caption="Desenmascarando algunas cosas">
# <i>echo "sys-apps/hal" >> /etc/portage/package.keywords</i>
# <i>echo "sys-apps/pmount" >> /etc/portage/package.keywords</i>
# <i>echo "sys-apps/dbus" >> /etc/portage/package.keywords</i>
# <i>echo "sys-fs/cryptsetup-luks" >> /etc/portage/package.keywords</i>
# <i>echo "app-admin/gamin" >> /etc/portage/package.keywords</i>
</pre>

<p>
A lo mejor tiene instalado cryptsetup, que bloquea la instalación
de crypsetup-luks, así que haga:
</p>

<pre caption="Desinstalando cryptsetup">
# <i>emerge unmerge cryptsetup</i>
</pre>

<p>
Si tiene una versión antigua de hal instalada, haga rm -rf
/etc/hal/device.d . De todas formas, el ebuild se lo notificará, pero
hagámoslo ya, de una vez.
</p>

<pre caption="Preparando el emerge del paquete hal">
# <i>rm -rf /etc/hal/device.d/</i>
</pre>

<p>
Asegúrese que no tiene instalado el paquete app-admin/fam. Si es así,
desinstálelo:
</p>

<pre caption="Desinstalando fam">
# <i>rc-update del famd</i>
# <i>emerge unmerge fam</i>
</pre>

<p>
A continuación, la actualización, recompilando todo con los
parámetros USE nuevos, con --newuse. Una forma de hacerlo es con
<c>emerge -uDav --newuse world</c>.
</p>

<pre caption="Actualización con nuevos parámetros USE">
# <i>emerge -uDav --newuse world</i>
</pre>

<p>
Ahora tenemos que iniciar dbus y hal. Estos debe ser iniciados cada que
arranque la máquina.
</p>

<pre caption="Iniciando dbus, hal y gamin">
# <i>rc-update add hald default</i>
# <i>/etc/init.d/hald start</i>
</pre>

<p>
No olvide agregarse a sí mismo al grupo plugdev en
<path>/etc/group</path>.
</p>

<p>
Ahora podrá iniciar el <c>gnome-volume-manager</c> desde la línea de
comando e insertar un pendrive USB, observar cómo se monta
automáticamente y colocar un ícono en el escritorio :)
</p>

<p>
Una manera que gnome-volume-manager ejecute al iniciar la sesión es ir
al Menú de Preferencias -> Sesiones y seleccionar la pestaña de
Programas al Inicio y agregar al <c>gnome-volume-manager</c>. Si desea
cambiar el comportamiento del gnome-volume-manager, inicie
<c>gnome-volume-properties</c> desde la línea de comando.
</p>
</body>
</section>
</chapter>

<chapter>
<title>¿Falló algo al compilar?</title>
<section>
<title>¿Alguien más ha visto algo semejante?</title>
<body>

<p>
Antes que nada, ¿el error se parece a alguno de estos?
</p>

<pre caption="Errores">
make[2]: Entering directory
`/var/tmp/portage/gnome-desktop-2.11.90/work/gnome-desktop-2.11.90/desktop-docs'
 Making all in fdl
 C/fdl.xml:603: parser error : Entity 'copy' not defined
         Copyright copy; YEAR YOUR NAME.
	                         ^
make[3]: Entering directory
`/var/tmp/portage/gnome-desktop-2.11.90/work/gnome-desktop-2.11.90/desktop-docs/fdl'
xsltproc -o fdl-C.omf --stringparam db2omf.basename fdl --stringparam
db2omf.format 'docbook' --stringparam db2omf.dtd "-//OASIS//DTD DocBook XML
V4.1.2//EN" --stringparam db2omf.lang C --stringparam db2omf.omf_dir
"/usr/share/omf" --stringparam db2omf.help_dir "/usr/share/gnome/help"
--stringparam db2omf.omf_in "`pwd`/./fdl.omf.in" `/usr/bin/pkg-config --variable
db2omf gnome-doc-utils` C/fdl.xml
compilation error: file C/fdl.xml line 15 element article
xsltParseStylesheetProcess : document is not a stylesheet
make[3]: *** [fdl-C.omf] Error 5
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
</pre>

<note>Vea <uri>http://bugs.gentoo.org/103322</uri> si este es el problema.
</note>

<note>En pocas palabras, debe re-emerger el paquete gnome-doc-utils
tal como hemos dicho anteriormente.
</note>

<pre caption="Más errores">
Traceback (most recent call last):
  File "/usr/bin/xml2po", line 34, in ?
      import libxml2
      ImportError: No module named libxml2
      make[2]: *** [de/file-roller.xml] Error 1
      make[2]: *** Waiting for unfinished jobs....
      Traceback (most recent call last):
        File "/usr/bin/xml2po", line 34, in ?
	    import libxml2
	    ImportError: No module named libxml2
make[2]: *** [es/file-roller.xml] Error 1
make[2]: Leaving directory
`/var/tmp/portage/file-roller-2.11.92/work/file-roller-2.11.92/help'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory
`/var/tmp/portage/file-roller-2.11.92/work/file-roller-2.11.92'
make: *** [all] Error 2
</pre>

<pre caption="Aún más errores">
ACCESS DENIED  unlink:    /usr/share/xml2po/docbook.pyc
ACCESS DENIED  open_wr:   /usr/share/xml2po/docbook.pyc
ACCESS DENIED  unlink:    /usr/share/xml2po/docbook.pyc
ACCESS DENIED  open_wr:   /usr/share/xml2po/docbook.pyc
</pre>

<note>Vea <uri>http://bugs.gentoo.org/104088</uri> si le ocurren
cualquiera de estos errores.
</note>
</body>
</section>

<section>
<title>¿Qué tal si no es uno de los errores antes mencionados?</title>
<body>

<p>
Por favor, revise en <uri>http://bugs.gentoo.org/103197</uri> a ver si
ya se ha reportado un fallo de GNOME 2.12 para el mismo problema:

</p>

<p>
El paso siguiente es buscar el nombre del paquete en bugzilla para
verificar si alguien ya ha publicado un bug. Si después de buscar
durante un par de años (jeje, echando broma) y no encontrar un bug
similar, por favor, ingrese uno (vea a continuación).
</p>

<p>
Si desea saber como ingresar un bug, por favor consulte el documento <uri>http://www.gentoo.org/doc/es/bugzilla-howto.xml</uri>.
</p>

<p>
También estamos a la órden en el canal #gentoo-desktop.
</p>
</body>
</section>
</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/news/20041021-statusgdp.xml
<?xml version='1.0'?>

<!DOCTYPE news SYSTEM "/dtd/guide.dtd">

<news gentoo="yes" category="main">
<poster>swift</poster>
<date>21 October 2004</date>
<title>Gentoo Documentation Project Status Update</title>

<body>

<p>
The <uri link="/proj/en/gdp">Gentoo Documentation Project</uri> has released a
new <uri link="/proj/en/gdp/status/status_20041021.xml">Status Update</uri>.
Most noticeable is an update to the <uri link="/doc/en/handbook">Gentoo
Handbook</uri> which now contains a part on <uri
link="/doc/en/handbook/handbook-x86.xml?part=3">Working with Portage</uri>.
</p>

</body>
</news>

=== ulm/gentoo-historical/xml/htdocs/proj/fr/base/x86/gcc-upgrading-guide.xml
<?xml version='1.0' encoding="UTF-8"?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/fr/base/x86/gcc-upgrading-guide.xml,v 1.4 2005/12/21 10:39:14 neysx Exp $ -->

<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="gcc-upgrading-guide.xml" disclaimer="obsolete" redirect="/doc/fr/gcc-upgrading.xml" lang="fr">
<title>Mise à jour de GCC pour Gentoo Linux</title>

<author title="Author">
  <mail link="jkt@gentoo.org">Jan Kundrát</mail>
</author>

<abstract>
Ce guide a été remplacé par une autre version.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>2.0</version>
<date>2005-12-08</date>

<chapter>
<title>Avertissement</title>
<section>
<body>

<p>
Ce guide a été étendu et remplacé par une <uri
link="/doc/fr/gcc-upgrading.xml">version plus générique</uri>.  Veuillez
consulter la nouvelle version.
</p>

</body>
</section>
</chapter>
</guide>
