=== ulm/gentoo-historical/xml/old-web/dtd/guide.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>

<!ENTITY  % content.class	"figure|fig|img|br|note|impo|warn|i|b|brite|c|box|pre|path|uri|p|e|mail|table|ul|ol">

<!ELEMENT guide			(title, subtitle?, author+, abstract, version, date, newsitems?, chapter+)>
<!ATTLIST guide			type (project) #IMPLIED
						link CDATA #IMPLIED
						mainpage (yes|no) "no"
						mainid (news|about|contract|packages|graphics|articles|docs|changelog|projects) #IMPLIED>
<!ELEMENT newsitems		(news+)>
<!ELEMENT news			(poster, date, title, body)>
<!ATTLIST news			gentoo (yes|no) "no"
						category (gentoo|main|ibm|linux|moo|nvidia) #REQUIRED>
<!ELEMENT title			(#PCDATA)>
<!ELEMENT subtitle		(#PCDATA)>
<!ELEMENT author		(mail)>
<!ATTLIST author		title CDATA #REQUIRED>
<!ELEMENT mail			(#PCDATA)>
<!ATTLIST mail			link CDATA #REQUIRED>
<!ELEMENT abstract		(#PCDATA)>
<!ELEMENT version		(#PCDATA)>
<!ELEMENT date			(#PCDATA)>
<!ELEMENT chapter		(title, section+)>
<!ELEMENT section		(title?, body)>
<!ELEMENT body			(%content.class;)*>
<!ELEMENT figure		(EMPTY)>
<!ATTLIST figure		caption CDATA #IMPLIED
						short CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT fig			(EMPTY)>
<!ATTLIST fig			short CDATA #IMPLIED
						linkto CDATA #IMPLIED
						link CDATA #REQUIRED>
<!ELEMENT img			EMPTY>
<!ATTLIST img			src CDATA #REQUIRED>
<!ELEMENT br			(#PCDATA)>
<!ELEMENT note			(#PCDATA)>
<!ELEMENT impo			(#PCDATA)>
<!ELEMENT warn			(#PCDATA)>
<!ELEMENT codenote		(#PCDATA)>
<!ELEMENT comment		(#PCDATA)>
<!ELEMENT i				(#PCDATA)>
<!ELEMENT b				(#PCDATA)>
<!ELEMENT brite			(#PCDATA)>
<!ELEMENT c				(#PCDATA)>
<!ELEMENT box			(#PCDATA)>
<!ELEMENT pre			(#PCDATA)>
<!ATTLIST pre			caption CDATA #IMPLIED>
<!ELEMENT path			(#PCDATA)>
<!ELEMENT uri			(#PCDATA)>
<!ATTLIST uri			link CDATA #IMPLIED>
<!ELEMENT p				(#PCDATA|%content.class;)*>
<!ELEMENT e				(#PCDATA)>
<!ELEMENT table			(tr+)>
<!ELEMENT tr			(th+|ti+)>
<!ELEMENT th			(#PCDATA|%content.class;)*>
<!ELEMENT ti			(#PCDATA|%content.class;)*>
<!ELEMENT ul			(li+)>
<!ELEMENT ol			(li+)>
<!ELEMENT li			(#PCDATA|%content.class;)*>

=== ulm/gentoo-historical/xml/htdocs/proj/en/desktop/gnome/faq.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/en/desktop/gnome/faq.xml,v 1.2 2006/11/09 21:42:59 nightmorph Exp $ -->

<guide link="/proj/en/desktop/gnome/faq.xml">
<title>Gentoo GNOME Project FAQ</title>

<author title="Author">
  <mail link="allanonjl@gentoo.org">John N. Laliberte</mail>
</author>

<author title="Author">
  <mail link="dang@gentoo.org">Daniel Gryniewicz</mail>
</author>

<abstract>
Frequently Asked Questions about GNOME on Gentoo.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>0.1</version>
<date>2004-08-03</date>

<chapter>
<title>Gentoo GNOME FAQ</title>
<section>
<title>Frequently Asked Questions</title>
<body>

<ol>
  <li>
    <uri link="#doc_chap1_sect2">How do I turn off desktop icons?</uri>
  </li>
  <li>
    <uri link="#doc_chap1_sect3">How do I use Keychain with GNOME?</uri>
  </li>
  <li>
    <uri link="#doc_chap1_sect4">Why doesn't USE="-gtk gtk2" work?</uri>
  </li>
  <li>
    <uri link="#doc_chap1_sect5">What is FAM, and should I use gamin
    instead?</uri>
  </li>
</ol>

</body>
</section>
<section>
<title>How do I turn off desktop icons?</title>
<body>		

<p>
Desktop icons are drawn by Nautilus. In order to remove them, you have to stop
nautilus from drawing the desktop. The quickest way is to modify the Nautilus
GConf key to controlling drawing. You can either use <c>gconf-editor</c> or
<c>gconftool-2</c> to set the
<path>/apps/nautilus/preferences/show_desktop</path>.
</p>

<pre caption="using gconftool-2">
% gconftool-2 -s /apps/nautilus/preferences/show_desktop -t bool false
</pre>

</body>
</section>
<section>
<title>How do I use Keychain with GNOME?</title>
<body>

<p>
<uri link="http://www.gentoo.org/proj/en/keychain.xml">Keychain</uri> manages
your SSH keys and SSH agent for you. To use it with your GNOME session, you will
need to install <c>gtk2-ssh-askpass</c> or <c>x11-ssh-askpass</c>. These give an
X interface to prompting you for a passphrase. Setup Keychain as the guide
suggests and you should be prompted for your passphrase on your next login.
</p>

</body>
</section>
<section>
<title>What is FAM, and should I use gamin instead?</title>
<body>

<p>
<uri link="http://http://oss.sgi.com/projects/fam/">FAM</uri> (or the File
Alteration Monitor) is a daemon responsible for notifying GUI applications of
changes to files. Typically, on a GNOME desktop, this is used by nautilus (the
file manager), to keep file listings current with the underlying system - even
when modifications to the files are made from outside of nautilus.
</p>

<p>
In short, FAM watches your filesystem to make sure what nautilus displays is up
to date.
</p>

<p>
<uri link="http://www.gnome.org/~veillard/gamin/">Gamin</uri> (an alternative to
FAM), is library implementation of a subset of FAM's functionality, although
it's purpose in monitoring the file system for changes, is the same.  Gamin is
not a complete FAM replacement - some of FAM's more exotic features are missing,
but Gamin's main aims are to be an API/ABI compatible replacement for FAM, and
to address resource consumption issues.
</p>

<p>
So which of these two should you choose?
</p>

<p>
We'd recommend you use Gamin over FAM for your GNOME desktop. The project is now
more mature, it doesn't need to run as a daemon (saving some resources), and is
easier to use than FAM.
</p>

<p>
If you don't have FAM installed, installing gamin is easy:
</p>

<pre caption="Installing gamin">
# <i>emerge gamin</i>
</pre>

<p>
If you already have FAM installed, it's still easy to switch to gamin.  You'll
need to stop FAM, remove it, and then install gamin:
</p>

<pre caption="Replacing FAM with gamin">
# <i>rc-update del famd default</i>
# <i>/etc/init.d/famd stop</i>
# <i>emerge -C fam</i>
# <i>emerge gamin</i>
</pre>

<p>
Now you'll just need to restart GNOME, or nautilus (<c>killall -9 nautilus</c>)
to use Gamin for file-monitoring.
</p>

</body>
</section>
</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/doc/lt/gentoo-x86-quickinstall.xml
<?xml version='1.0' encoding="UTF-8"?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/lt/gentoo-x86-quickinstall.xml,v 1.3 2009/01/31 09:00:48 neysx Exp $ -->

<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide lang="lt">
<title>„Gentoo Linux“ x86 greitojo diegimo vadovas</title>

<values>
 <key id="raid+lvm">no</key>
 <key id="root">/dev/sda3</key>
</values>

<author title="Autorius">
  <mail link="neysx"/>
</author>
<author title="Autorius">
  <mail link="swift"/>
</author>
<author title="Autorius">Steven Wagner</author>
<author title="Vertėjas">
  <mail link="e.liubarskij@gmail.com">Ernestas Liubarskij</mail>
</author>

<abstract>
Greitojo diegimo vadove glaustai aprašomas „Gentoo“ diegimo procesas. Jo
paskirtis - leisti naudotojams labai greitai atlikti stage3 diegimą. Naudotojai
turėtų jau turėti ankstesnės patirties „Gentoo Linux“ diegime, jei nori sekti
šiuo vadovu.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>23</version>
<date>2009-01-09</date>

<chapter>
<title>Įvadas</title>
<section>
<body>

<p>
Šiame vadove yra visos komandos, kurias turėtumėte naudoti stage3 „Gentoo“
diegimo užbaigimui. Stage3 ir „Portage“ momentinių kopijų atsisiuntimui jums
reikės veikiančio internetinio ryšio.
</p>

<p>
Nauji naudotojai turėtų skaityti <uri link="/doc/en/handbook/index.xml">pilną
vadovą</uri>, kadangi jame diegimo procesas apžvelgiamas plačiau.
</p>

<p>
Laikas, per kurį įvykdoma komanda, kurios vykdymui reikia daugiau nei kelių
sekundžių, išvedamas po kiekvienos tokios komandos. Komandų vykdymo laikas
buvo apskaičiuotas AMD 2000 1.66 Ghz kompiuteriu su 512 MB laisvosios kreipties
atmintine (RAM) ir dviem prijungtais prie aparatinio valdiklio SATA diskais.
</p>

<pre caption="Kompiuterio specifikacijos patikrinimas">
<comment>(Ši specifikacija ir laiko apskaitos informacija turėtų padėti jums
nustatyti apytikrį apskaičiavimą laiko, reikiamo diegimo užbaigimui)</comment>

# <i>grep bogo /proc/cpuinfo</i>
bogomips       : 3337.81

# <i>hdparm -tT /dev/sda</i>
/dev/sda:
 Timing cached reads:   1100 MB in  2.00 seconds = 549.97 MB/sec
 Timing buffered disk reads:  224 MB in  3.01 seconds =  74.36 MB/sec

# <i>grep MemTotal /proc/meminfo</i>
MemTotal:       509248 kB
</pre>

</body>
</section>
</chapter>

<chapter>
<title>Greitojo diegimo vadovas</title>

<section>
 <include href="gentoo-x86-quickinstall-media.xml"/>
</section>

<section>
<title>Diskų paruošimas</title>
<body>

<p>
Skaidinių išdėstymo (partition layout) sukūrimui naudokite <c>fdisk</c> arba
<c>cfdisk</c>. Reikės bent jau keitinių (swap) skaidinio (82 tipas) ir vieno
„Linux“ skaidinio (83 tipas). Šiuo scenarijumi sukuriamas <path>/boot</path>,
keitinių ir pagrindinis skaidiniai, kaip naudojama mūsų vadove. Pakeiskite
<path>sda</path> savo disku. Dauguma sistemų ignoruoja įkraunamo (bootable)
skaidinio vėliavėlę, tačiau kai kurioms jo visgi reikia. Nustatykite šią
vėliavėlę savo įkraunamam skaidiniui, naudodami „fdisk“ komandą <c>a</c>.
</p>

<pre caption="Skaidinių sukūrimas">
livecd ~ # <i>fdisk /dev/sda</i>

<comment>(Likusioje vadovo dalyje naudojama ši skaidinių schema)</comment>
livecd ~ # <i>fdisk -l /dev/sda</i>

Disk /dev/sda: 599.9 GB, 599978409984 bytes
255 heads, 63 sectors/track, 72943 cylinders
Units = cylinders of 16065 * 512 = 8225280 bytes

   Device Boot      Start         End      Blocks   Id  System
/dev/sda1  *            1          12       96358+  83  Linux
/dev/sda2              13         110      787185   82  Linux swap / Solaris
/dev/sda3             111       72943   585031072+  83  Linux
</pre>

<p>
Rinkmenų išdėstymo sistemų savo „Linux“ skaidiniuose sukūrimui naudokite
<c>mke2fs</c>, <c>mke2fs -j</c>, <c>mkreiserfs</c>, <c>mkfs.xfs</c> ir
<c>mkfs.jfs</c>. Inicijuokite keitinių skaidinį naudodamiesi <c>mkswap</c> ir
<c>swapon</c>.
</p>

<pre caption="Rinkmenų išdėstymo sistemų sukūrimas ir keitinių aktyvavimas">
<comment>(ext2 yra viskas, ko jums reikia /boot skaidinyje)</comment>
livecd ~ # <i>mke2fs /dev/sda1</i>

<comment>(Pagrindiniame skaidinyje naudokime ext3)</comment>
livecd ~ # <i>mke2fs -j /dev/sda3</i>

<comment>(Keitinių sukūrimas ir aktyvavimas)</comment>
livecd ~ # <i>mkswap /dev/sda2 &amp;&amp; swapon /dev/sda2</i>
</pre>

<p>
Prijunkite naujai sukurtas rinkmenų išdėstymo sistemas prie
<path>/mnt/gentoo</path>. Sukurkite katalogus kitiems jungties taškams
(pavyzdžiui, <path>/mnt/gentoo/boot</path>), jei jums jų reikia ir juos taip
pat prijunkite.
</p>

<pre caption="Rinkmenų išdėstymo sistemų prijungimas">
livecd ~ # <i>mount /dev/sda3 /mnt/gentoo</i>
livecd ~ # <i>mkdir /mnt/gentoo/boot</i>
livecd ~ # <i>mount /dev/sda1 /mnt/gentoo/boot</i>
livecd ~ # <i>cd /mnt/gentoo</i>
</pre>

</body>
</section>

<section>
 <include href="gentoo-x86-quickinstall-stage.xml"/>
</section>

<section>
<title>Branduolio konfigūravimas</title>
<body>

<p>
Įdiekite branduolio pirminį tekstą (paprastai <c>gentoo-sources</c>),
sukonfigūruokite, sukompiliuokite jį ir nukopijuokite
<path>arch/i386/boot/bzImage</path> rinkmeną į <path>/boot</path>.
</p>

<pre caption="Įdiekite branduolio pirminį tekstą, sukompiliuokite jį ir įdiekite branduolį">
livecd etc # <i>time emerge gentoo-sources</i>

real  2m51.435s
user  0m58.220s
sys   0m29.890s
livecd etc # <i>cd /usr/src/linux</i>
livecd linux # <i>make menuconfig</i>
<comment>(Sukonfigūruokite savo branduolį)</comment>
livecd linux # <i>time make -j2</i>

<comment>(Laikas labai priklauso jūsų pažymėtų parinkčių)</comment>
real  3m51.962s
user  3m27.060s
sys   0m24.310s

livecd linux # <i>make modules_install</i>
livecd linux # <i>cp arch/i386/boot/bzImage /boot/kernel</i>
</pre>

</body>
</section>

<section>
 <include href="gentoo-x86-quickinstall-system.xml"/>
</section>

<section id="reboot">
<title>Perkrovimas</title>
<body>

<p>
Išeikite iš pakeisto šakninio katalogo aplinkos, atjunkite visas rinkmenų
išdėstymo sistemas ir perkraukite kompiuterį:
</p>

<pre caption="Perkrovimas">
livecd conf.d # <i>exit</i>
livecd / # <i>umount /mnt/gentoo/proc /mnt/gentoo/boot /mnt/gentoo</i>
livecd / # <i>reboot</i>
<comment>(Nepamirškite išimti CD)</comment>
</pre>

</body>
</section>

<section>
 <include href="gentoo-x86-quickinstall-after-reboot.xml"/>
</section>

</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/doc/de/gnome-config.xml
<?xml version='1.0' encoding='UTF-8'?>

<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/de/gnome-config.xml,v 1.1 2004/12/24 13:17:51 dertobi123 Exp $ -->

<!-- English CVS Version: 1.1 -->

<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide link="/doc/de/gnome-config.xml">

<title>Konfigurationsanleitung für Gnome</title>

<author title="Autor">
  <mail link="swift@gentoo.org">Sven Vermeulen</mail>
</author>
<author title="Übersetzer">
  <mail link="rk@oppono.de">Robert Körner</mail>
</author>

<abstract>
GNOME ist eine viel genutzte Arbeitsumgebung. Diese Anleitung versucht, alle
Aspekte GNOME's zu beschreiben - Installation, Konfiguration, Benutzung, ... 
eingeschlossen.
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/1.0 -->
<license/>

<version>1.1</version>
<date>2004-05-12</date>

<chapter>
<title>Was ist GNOME?</title>
<section>
<title>Das Projekt</title>
<body>

<p>
Das <uri link="http://www.gnome.org">GNOME</uri>-Projekt ist ein freies
Softwareprojekt, engagiert in der Entwicklung von GNOME, einer
Unix/Linux-Desktopsuite und -Entwicklungsplattform. Die <uri
link="http://foundation.gnome.org">GNOME Foundation</uri> koordiniert die
Entwicklung und andere Aspekte des GNOME-Projektes.
</p>

</body>
</section>
<section>
<title>Die Software</title>
<body>

<p>
GNOME ist eine Desktopumgebung und Entwicklungsplattform. Dieses Stück 
freie Software ist von mehreren führenden Firmen der Industrie als <e>die</e>
Desktopumgebung erkoren worden. Es ist sowohl für Business-Benutzer, 
Privatanwender als auch für Entwickler sehr interessant.
</p>

</body>
</section>
<section>
<title>Die Community</title>
<body>

<p>
Wie jedes große Projekt auf der Grundlage freier Software, hat auch GNOME eine
große Basis an Benutzern und Entwicklern. <uri
link="http://www.gnomedesktop.org">Footnotes</uri> beinhaltet GNOME-Desktop News
für Anwender; <uri link="http://planet.gnome.org">GnomePlanet</uri> ist für
Hacker/Mitwirkende und <uri link="http://developer.gnome.org">
Developer.Gnome.Org</uri> ist für GNOME Entwickler.
</p>

</body>
</section>
</chapter>
<chapter>
<title>Installation von GNOME</title>
<section>
<title>Was wird gebraucht?</title>
<body>

<p>
Bevor Sie mit der Installation von GNOME beginnen, sollten Sie evtl. Ihre
USE-Variable editieren. Stellen Sie sicher, dass <c>gtk</c> und <c>gnome</c> in
Ihrer USE-Variable enthalten sind, zu finden in der Datei
<path>/etc/make.conf</path>. Wenn Sie keine KDE-Unterstützung möchten (die
andere große Desktopumgebung), entfernen Sie <c>qt</c> und <c>kde</c> aus Ihrer
USE.
</p>

<pre caption="Beispiel-USE in /etc/make.conf">
USE="-qt -kde gtk gnome"
</pre>

<p>
Wenn Sie damit fertig sind, beginnen Sie die GNOME-Installation, indem Sie 
<c>gnome</c> und <c>xscreensaver</c> kompilieren:
</p>

<pre caption="Installation von GNOME">
# <i>emerge gnome xscreensaver</i>
</pre>

<p>
Dies wird einen Moment dauern. Wärend die Installation fortschreitet, können Sie
all jene Bücher lesen, derer Sie habhaft werden können (es dauert wirklich 
ziemlich lang). Fertig? Wunderbar, jetzt aktualisieren Sie Ihre 
Umgebungsvariablen:
</p>

<pre caption="Aktualisierung der Umgebungsvariablen">
# <i>env-update &amp;&amp; source /etc/profile</i>
</pre>

<p>
Wenn Sie der Ausgabe des vorhergegangenen <c>emerge</c>-Befehls Aufmerksamkeit
geschenkt haben, werden Sie bemerkt haben, dass empfohlen wird, <c>famd</c> zum
Standard-Runlevel hinzuzufügen, damit nautilus und gnome-vfs-monitor 
Dateiänderungen protokollieren können:
</p>

<pre caption="Hinzufügen von famd zum Standard-Runlevel (default)">
# <i>/etc/init.d/famd start</i>
# <i>rc-update add famd default</i>
</pre>

</body>
</section>
<section>
<title>Erste Eindrücke</title>
<body>

<p>
Lassen Sie uns zuerst anschauen, was gerade kompiliert wurde. Verlassen Sie
Ihre Root-Shell und loggen Sie sich als normaler Benutzer ein. Wir werden 
unsere Session so konfigurieren, dass GNOME gestartet wird, wenn wir den 
<c>startx</c>-Befehl ausführen:
</p>

<pre caption="GNOME als Standard-Desktopumgebung">
$ <i>echo "exec gnome-session" &gt; ~/.xinitrc</i>
</pre>

<p>
Starten Sie jetzt Ihre grafische Umgebung durch ausführen von <c>startx</c>:
</p>

<pre caption="Starten von GNOME">
$ <i>startx</i>
</pre>

<p>
Wenn alles glatt läuft, sollten Sie von GNOME begrüßt werden. Herzlichen
Glückwunsch! Jetzt lassen Sie uns jedoch einen Blick auf die Möglichkeiten 
werfen, GNOME Ihren persönlichen Wünschen anzupassen:
</p>

</body>
</section>
</chapter>
<chapter>
<title>Konfiguration von GNOME</title>
<section>
<title>GNOMEs grafischer Login-Manager</title>
<body>

<p>
Wenn Sie den "GNOME Display Manager" (GDM) bei Systemstart automatisch gestartet
haben möchten (so dass Sie sich graphisch einloggen können), müssen Sie das 
<c>xdm</c>-Initscript zum Standard-Runlevel hinzufügen:
</p>

<pre caption="Hinzufügen von xdm zum Standard-Runlevel (default)">
# <i>rc-update add xdm default</i>
</pre>

<p>
Überprüfen Sie jetzt den Inhalt von <path>etc/X11/Sessions</path>:
</p>

<pre caption="Überprüfen von /etc/X11/Sessions">
# <i>ls /etc/X11/Sessions</i>
Xsession Gnome
</pre>

<p>
Wie Sie sehen, ist eine Session (Sitzung) namens <c>gnome</c> vorhanden. Jetzt
editieren Sie <path>/etc/rc.conf</path> und passen zwei Variablen an: 
DISPLAYMANAGER (die auf <c>gdm</c> gesetzt werden sollte) und XSESSION (welche 
auf <c>Gnome</c> gesetzt werden sollte):
</p>

<pre caption="/etc/rc.conf editieren">
DISPLAYMANAGER="gdm"
XSESSION="Gnome"
</pre>

<p>
Wenn Sie jetzt Ihren Rechner neu starten, wird der GNOME Display Manager
Benutzername und Passwort von Ihnen einfordern und als Default-Einstellung
GNOME als Desktopumgebung verwenden (obgleich Sie natürlich auch einen anderen
einstellen können).
</p>

</body>
</section>
</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/proj/en/desktop/x/x11/xorg-server-1.9-upgrade-guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/en/desktop/x/x11/xorg-server-1.9-upgrade-guide.xml,v 1.3 2012/10/28 15:21:02 swift Exp $ -->

<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">

<guide>
<title>Xorg-server 1.9 Upgrade Guide</title>

<author title="Author">
	<mail link="scarabeus"/>
</author>

<author title="Editor">
	<mail link="remi"/>
</author>

<author title="Editor">
	<mail link="chithanh"/>
</author>

<abstract>
This guide shows you how to upgrade X.org server to version 1.9.
</abstract>

<!-- The  content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1</version>
<date>2010-09-22</date>

<chapter>
<title>Features changes</title>
<section>
<body>

<ul>
	<li>
		Xorg can detect input devices using udev, removing its HAL support.
		Users who used HAL before need to migrate to udev.
	</li>
</ul>

</body>
</section>
</chapter>

<chapter>
<title>Migrating from xorg-server 1.8</title>
<section>
<body>
<p>
The primary difference is that the deprecated HAL support has now been removed
in favor of udev. If you already used udev before, then no action is necessary.
If you used HAL with <c>xorg-server-1.8</c> then read on.
</p>
</body>
</section>
</chapter>

<chapter>
<title>Migrating from xorg-server 1.7 or 1.8 with HAL</title>
<section>
<body>
<p>
Enabling udev just requires building <c>xorg-server</c> with <c>USE="udev"</c>.
Systems which worked fine with the default HAL fdi will not need special
configuration. If you created custom fdi files, then refer to the <uri
link="xorg-server-1.8-upgrade-guide.xml">Xorg-server 1.8 Upgrade Guide</uri>
how to migrate your configuration to udev.
</p>
</body>
</section>
</chapter>

</guide>

=== ulm/gentoo-historical/xml/htdocs/proj/en/hardened/selinux/modules/ssh.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/en/hardened/selinux/modules/Attic/ssh.xml,v 1.1 2011/07/16 20:36:41 zorry Exp $ -->

<guide link="/proj/en/hardened/selinux/modules/ssh.xml" disclaimer="draft" lang="en">
<title>SELinux SSH Module</title>
<author title="Author">
  <mail link="sven.vermeulen@siphos.be">Sven Vermeulen</mail>
</author>

<abstract>
Within SELinux, the SSH module is responsible for defining what openssh can do
</abstract>

<!-- The content of this document is licensed under the CC-BY-SA license -->
<!-- See http://creativecommons.org/licenses/by-sa/2.5 -->
<license/>

<version>1</version>
<date>2011-07-09</date>

<chapter>
<title>Structure</title>
<section>
<title>Domains</title>
<body>

<figure link="./images/sshdomain.png" short="General SSH domain overview"
caption="General SSH domain overview" />

<p>
The...
</p>

</body>
</section>
<section>
<title>File Types/Labels</title>
<body>

<p>
The following table lists the file type/labels defined in the <c>ldap</c>
module.
</p>

<table>
<tr>
  <th>Type</th>
  <th>Function</th>
  <th>Description</th>
</tr>
<tr>
  <ti>slapd_exec_t</ti>
  <ti>Entrypoint</ti>
  <ti>Executable entry point for the slapd daemon binaries</ti>
</tr>
<tr>
  <ti>slapd_etc_t</ti>
  <ti>Configuration</ti>
  <ti>Label for OpenLDAP configuration files</ti>
</tr>
<tr>
  <ti>slapd_cert_t</ti>
  <ti>Configuration</ti>
  <ti>Label for certificate keystores used by OpenLDAP</ti>
</tr>
<tr>
  <ti>slapd_db_t</ti>
  <ti>Configuration</ti>
  <ti>Label for the OpenLDAP database files (backend content)</ti>
</tr>
<tr>
  <ti>slapd_replog_t</ti>
  <ti>Configuration</ti>
  <ti>Label for the slurpd replication log location</ti>
</tr>
<tr>
  <ti>slapd_lock_t</ti>
  <ti></ti>
  <ti>Label for the lock files (runtime)</ti>
</tr>
<tr>
  <ti>slapd_tmp_t</ti>
  <ti></ti>
  <ti>Label for the temporary files</ti>
</tr>
<tr>
  <ti>slapd_var_run_t</ti>
  <ti></ti>
  <ti>Label for the runtime variable data</ti>
</tr>
<tr>
  <ti>slapd_initrc_exec_t</ti>
  <ti></ti>
  <ti>Label for non-Gentoo init script</ti>
</tr>
</table>

</body>
</section>
</chapter>
</guide>

=== ulm/gentoo-historical/xml/htdocs/doc/ro/gentoo-security.xml
<?xml version='1.0' encoding='UTF-8'?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/doc/ro/gentoo-security.xml,v 1.7 2012/06/30 18:51:13 swift Exp $ -->

<!DOCTYPE guide SYSTEM "/dtd/guide.dtd">
<guide disclaimer="obsolete" lang="ro" redirect="/doc/en/security/">
<title>Fostul Ghid pentru Securitate în Gentoo Linux</title>
<author title="Autor">
  <mail link="neysx@gentoo.org">Xavier Neys</mail>
</author>
<author title="Translator">
  <mail link="alin@gentoo.org">Alin Dobre</mail>
</author>

<abstract>
Acesta este un ghid pas-cu-pas pentru securizarea Gentoo Linux.
</abstract>

<version>1.0</version>
<date>2005-06-01</date>

<chapter>
<title>Clasat</title>
<section>
<body>

<p>
Acest ghid a fost înlocuit de <uri link="/doc/ro/security/">Manualul pentru
Securitate în Gentoo</uri>.
</p>

</body>
</section>
</chapter>
</guide>
