=== ulm/gentoo-historical/xml/htdocs/dtd/election.dtd
<!ELEMENT election (title, author*, abstract?, date, version?, nominee*)>
<!ELEMENT title         (#PCDATA)*>
<!ELEMENT author        (#PCDATA|mail)*>
<!ATTLIST author        title CDATA #IMPLIED>
<!ELEMENT mail          (#PCDATA)*>
<!ATTLIST mail    link  CDATA #IMPLIED>
<!ELEMENT abstract      (#PCDATA)>
<!ELEMENT date          (#PCDATA)>
<!ELEMENT version       (#PCDATA)>
<!ELEMENT nominee (#PCDATA)>
<!ATTLIST nominee accepted (yes|no) #IMPLIED
                  devrel   (yes|no) #IMPLIED
                  council  (yes|no) #IMPLIED
                  trustee  (yes|no) #IMPLIED>

=== ulm/gentoo-historical/xml/htdocs/proj/en/elections/council/2013/council-201306-nominees.xml
<?xml version='1.0' encoding="UTF-8"?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/en/elections/council/2013/council-201306-nominees.xml,v 1.1 2013/06/18 12:15:05 jmbsvicetto Exp $ -->
<!DOCTYPE election SYSTEM "/dtd/election.dtd">
<?xml-stylesheet href="/xsl/election.xsl" type="text/xsl"?>
<?xml-stylesheet href="/xsl/guide.xsl" type="text/xsl"?>

<election>
    <title>Gentoo Council 2013/2014 Nominations</title>

<author title="Election Official">
  <mail link="jmbsvicetto"/>
</author>
<author title="Election Official">
  <mail link="neddyseagoon"/>
</author>
<author title="Election Official">
  <mail link="tampakrap"/>
</author>
<author title="Election Official / Infrastructure Contact">
  <mail link="robbat2"/>
</author>

<date>2013-06-18</date>
<version>1</version>

<nominations from="2013-06-15" to="2013-06-28">

<!-- These folks accepted -->
<!-- <nominee accepted="yes" platform=" " council="yes" devrel="yes" trustee="no">NAME</nominee> -->
<nominee accepted="yes"
  platform=""
  council="yes" devrel="no" trustee="no">chainsaw</nominee>
<nominee accepted="yes"
  platform=""
  council="no" devrel="no" trustee="no">floppym</nominee>
<nominee accepted="yes"
  platform=""
  council="no" devrel="no" trustee="no">nirbheek</nominee>
<nominee accepted="yes"
  platform=""
  council="yes" devrel="no" trustee="no">ulm</nominee>
<nominee accepted="yes"
  platform=""
  council="yes" devrel="no" trustee="no">williamh</nominee>
<nominee accepted="yes"
  platform=""
  council="yes" devrel="no" trustee="no">zero_chaos</nominee>

<nominee > </nominee>


<!-- These folks didn't reply -->
<nominee council="no" devrel="no" trustee="no">axs</nominee>
<nominee council="yes" devrel="yes" trustee="no">betelgeuse</nominee>
<nominee council="no" devrel="no" trustee="no">blueness</nominee>
<nominee council="no" devrel="no" trustee="no">cardoe</nominee>
<nominee council="no" devrel="no" trustee="no">chithanh</nominee>
<nominee council="yes" devrel="no" trustee="no">dberkholz</nominee>
<nominee council="no" devrel="yes" trustee="no">dilfridge</nominee>
<nominee council="no" devrel="no" trustee="no">dolsen</nominee>
<nominee council="no" devrel="no" trustee="no">graaff</nominee>
<nominee council="yes" devrel="no" trustee="no">grobian</nominee>
<nominee council="no" devrel="yes" trustee="no">hwoarang</nominee>
<nominee council="no" devrel="yes" trustee="no">lu_zero</nominee>
<nominee council="no" devrel="no" trustee="no">maksbotan</nominee>
<nominee council="no" devrel="no" trustee="no">marienz</nominee>
<nominee council="no" devrel="no" trustee="no">mgorny</nominee>
<nominee council="no" devrel="no" trustee="no">patrick</nominee>
<nominee council="no" devrel="no" trustee="no">phajdan.jr</nominee>
<nominee council="no" devrel="no" trustee="no">polynomial-c</nominee>
<nominee council="no" devrel="no" trustee="no">ryao</nominee>
<nominee council="no" devrel="no" trustee="yes">rich0</nominee>
<nominee council="yes" devrel="no" trustee="no">scarabeus</nominee>
<nominee council="no" devrel="no" trustee="no">ssuominen</nominee>
<nominee council="no" devrel="no" trustee="no">swift</nominee>
<nominee council="no" devrel="no" trustee="no">tommy</nominee>
<nominee council="no" devrel="no" trustee="no">tomwij</nominee>
<nominee council="no" devrel="no" trustee="no">vapier</nominee>

<nominee > </nominee>


<!-- These folks declined the nomination -->
<!-- <nominee accepted="no" council="no" devrel="no" trustee="no">NAME</nominee> -->
<nominee accepted="no" council="no" devrel="yes" trustee="no">jmbsvicetto</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">johu</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">kensington</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">pacho</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">pinkbyte</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">radhermit</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">robbat2</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">tampakrap</nominee>
<nominee accepted="no" council="no" devrel="no" trustee="no">zmedico</nominee>


<!-- examples
  <nominee accepted="yes" platform="../council/voting-logs/nominees/2008/dev-zero.txt">dev-zero</nominee>
  <nominee accepted="yes" platform="../council/voting-logs/nominees/2008/dev-zero.txt" council="yes" devrel="yes">dev-zero</nominee>
  <nominee > </nominee>
-->

</nominations>
</election>
