=== ulm/gentoo-historical/xml/htdocs/dtd/project.dtd
<!-- import certain parts of guide.dtd -->
<!ENTITY  % style.class "b|box|brite|c|codenote|comment|e|i|path">
<!ENTITY  % link.class  "uri|mail">
<!ENTITY  % logic.class "figure|fig|img|br|note|impo|warn|pre|p|table|ul|ol">
<!ENTITY  % all.class   "%logic.class;|%style.class;|%link.class;">

<!-- allow for custom sections -->
<!ELEMENT title                 (#PCDATA|%style.class;)*>
<!ELEMENT chapter               (title, section+)>
<!ELEMENT section               (title?, body)>
<!ELEMENT body                  (%all.class;)*>


<!-- allow for layout etc. in some cases so define the classes -->
<!ELEMENT figure                EMPTY>
<!ATTLIST figure                caption CDATA #IMPLIED
                                short CDATA #IMPLIED
                                link CDATA #REQUIRED>
<!ELEMENT fig                   EMPTY>
<!ATTLIST fig                   short CDATA #IMPLIED
                                linkto CDATA #IMPLIED
                                link CDATA #REQUIRED>
<!ELEMENT img                   EMPTY>
<!ATTLIST img                   src CDATA #REQUIRED>
<!ELEMENT br                    (#PCDATA)>
<!ELEMENT note                  (#PCDATA|%all.class;)*>
<!ELEMENT impo                  (#PCDATA|%all.class;)*>
<!ELEMENT warn                  (#PCDATA|%all.class;)*>
<!ELEMENT pre                   (#PCDATA|%all.class;)*>
<!ATTLIST pre                   caption CDATA #IMPLIED>
<!ELEMENT p                     (#PCDATA|%all.class;)*>
<!ELEMENT table                 (tcolumn*, tr+)>
<!ELEMENT tcolumn               EMPTY>
<!ATTLIST tcolumn               width CDATA #REQUIRED>
<!ELEMENT tr                    (th|ti)+>
<!ELEMENT th                    (#PCDATA|%all.class;)*>
<!ELEMENT ti                    (#PCDATA|%all.class;)*>
<!ELEMENT ul                    (li+)>
<!ELEMENT ol                    (li+)>
<!ELEMENT li                    (#PCDATA|%all.class;)*>
<!ELEMENT b                     (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT brite                 (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT box                   (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT c                     (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT codenote              (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT comment               (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT e                     (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT i                     (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT path                  (#PCDATA|%style.class;|%link.class;)*>
<!ELEMENT mail                  (#PCDATA|%style.class;)*>
<!ATTLIST mail                  link CDATA #REQUIRED>
<!ELEMENT uri                   (#PCDATA|%style.class;)*>
<!ATTLIST uri                   link CDATA #IMPLIED>




<!ELEMENT project (name, longname?, date?, author*, description, longdescription, goals?, (dev | resource | subproject | plannedproject |extraproject | extrachapter |  herd | task | author)* )>
<!ELEMENT name (#PCDATA)>
<!ELEMENT longname (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT author		(#PCDATA|mail)*>
<!ATTLIST author		title CDATA #IMPLIED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT longdescription (#PCDATA |%all.class;)* >
<!ELEMENT goals (#PCDATA | %all.class; )* >
<!ELEMENT dev (#PCDATA)>
<!ATTLIST dev role CDATA "member"
	      description CDATA #IMPLIED>
<!ELEMENT resource (#PCDATA)>
<!ATTLIST resource link CDATA #IMPLIED>
<!ELEMENT subproject EMPTY>
<!ATTLIST subproject ref CDATA #REQUIRED
	             inheritmembers ( yes | no ) "no"
	             inheritresources ( yes | no ) "no" >
<!ELEMENT extraproject (#PCDATA | %all.class; )*>
<!ATTLIST extraproject name CDATA #REQUIRED
		       lead CDATA #IMPLIED >
<!ELEMENT plannedproject (#PCDATA | %all.class; )*>
<!ATTLIST plannedproject name CDATA #REQUIRED >
<!ELEMENT extrachapter               (title, section+)>
<!ATTLIST extrachapter position ( top | bottom |subproject|goals|resources|devs|tasks ) "bottom">
<!ELEMENT herd EMPTY>
<!ATTLIST herd name CDATA #REQUIRED>

<!-- TASK tags declaration -->
<!ELEMENT task ( name, description, longdescription?, startdate, enddate?, (reference | milestone | dev |depends )* )>
<!ATTLIST task id ID #IMPLIED
               lead CDATA #REQUIRED
               finished (yes | no) "no">
<!ELEMENT startdate (#PCDATA)>
<!ELEMENT enddate (#PCDATA)>
<!ELEMENT reference (#PCDATA | bug | %link.class;)* >
<!ELEMENT bug (#PCDATA)>
<!ATTLIST bug no CDATA #REQUIRED>
<!ELEMENT milestone (enddate, description)>
<!ATTLIST milestone finished (yes| no) "no">
<!ELEMENT depends (#PCDATA)>
<!ATTLIST depends ref IDREF #REQUIRED>

=== ulm/gentoo-historical/xml/htdocs/proj/en/base/ppc/index.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="/xsl/project.xsl" type="text/xsl"?>
<?xml-stylesheet href="/xsl/guide.xsl" type="text/xsl"?>
<!DOCTYPE project SYSTEM "/dtd/project.dtd">
<project>
  <name>Gentoo PowerPC</name>
  <longname>Gentoo Linux PowerPC Development</longname>
  <date>2010-01-22</date>

  <description>
    The Gentoo/PowerPC Project supports and maintains Gentoo Linux on the PowerPC
    architecture, for both the 32 bit and 64 bit userlands.
  </description>

  <longdescription>
  
    <p>The Gentoo/PowerPC Project works to ensure that Gentoo is the most up to 
    date and robust PowerPC distribution available for both server and desktop 
    applications.</p> 

    <p>Bugs are tracked and resolved from the 
    <uri link="http://bugs.gentoo.org">Gentoo bug tracker</uri>.  For PowerPC
    bugs, please see this <uri link="https://bugs.gentoo.org/buglist.cgi?query_format=&amp;short_desc_type=allwordssubstr&amp;short_desc=&amp;long_desc_type=substring&amp;long_desc=&amp;bug_file_loc_type=allwordssubstr&amp;bug_file_loc=&amp;keywords_type=allwords&amp;keywords=&amp;bug_status=NEW&amp;bug_status=ASSIGNED&amp;bug_status=REOPENED&amp;emailassigned_to1=1&amp;emailtype1=exact&amp;email1=ppc%40gentoo.org&amp;emailassigned_to2=1&amp;emailreporter2=1&amp;emailqa_contact2=1&amp;emailcc2=1&amp;emailtype2=substring&amp;email2=&amp;bugidtype=include&amp;bug_id=&amp;votes=&amp;changedin=&amp;chfieldfrom=&amp;chfieldto=Now&amp;chfieldvalue=&amp;cmdtype=doit&amp;order=Reuse+same+sort+as+last+time&amp;field0-0-0=noop&amp;type0-0-0=noop&amp;value0-0-0=">link</uri>. 
    Correspondence is maintained on the PowerPC related mailing lists,
    gentoo-ppc-user and gentoo-ppc-dev.  For more information on PowerPC mailing
    lists, please see <uri link="http://www.gentoo.org/main/en/lists.xml"> the
    Gentoo Mailing list overview</uri>. Additionally, the PowerPC team is almost
    always available in #gentoo-powerpc on 
    <uri link="http://freenode.net">freenode</uri>.</p>
    
  </longdescription>

  <goals>
  
    <p>The goal of the Gentoo PowerPC development project is to guarantee that
    the PowerPC packages built using Gentoo meta-data (ebuilds) are functional 
    and up to date.  By continuously testing new packages, maintaining 
    existing packages and providing user support, the Gentoo PowerPC team 
    provides the PowerPC user with a modern distro based on community, 
    performance and freedom.  Utilizing Gentoo's meta-data based distribution 
    allows a user to to be as bleeding edge or as conservative as is desired.
    </p>

    <p>Gentoo is unique because all of its supported architectures share the 
    same generic meta-data information (ebuilds) which describe how to build 
    packages.  These packages are combined to form the foundation of this 
    distribution.  The PowerPC developers are responsible for building and 
    testing ebuilds and marking them as tested (~ppc/~ppc64) or stable 
    (ppc/ppc64). Our users can use this information, along with the portage
    application, to build a system that suits their needs, whether it is a
    stable server, embedded system or a bleeding edge desktop system.</p>

  </goals>

  <subproject ref="/proj/en/base/ppc/doc.xml"/>

  <dev role="Developer" description="Gentoo/PPC">josejx</dev>
  <dev role="Developer" description="Gentoo/PPC">nixnut</dev>
  <dev role="Developer" description="Gentoo/PPC">volkmar</dev>

  <dev role="Developer" description="Gentoo/PPC64">tgall</dev>
  <dev role="Developer" description="Gentoo/PPC64">josejx</dev>
  <dev role="Developer" description="Gentoo/PPC64">ranger</dev>

  <extrachapter position="bottom">
    <title>How to Participate</title>
    <section>
      <body>

        <p>Can you make computers do amazing things? Are you excited about
        exploring areas of computing never explored before? We are continuously
        looking for volunteers willing to spend some of their free time on this
        project.</p>

        <p>If you are interested in helping, but don't have a niche that you are
        interested in filling, you can always look through our 
	<uri link="https://bugs.gentoo.org/buglist.cgi?query_format=&amp;short_desc_type=allwordssubstr&amp;short_desc=&amp;long_desc_type=substring&amp;long_desc=&amp;bug_file_loc_type=allwordssubstr&amp;bug_file_loc=&amp;keywords_type=allwords&amp;keywords=&amp;bug_status=NEW&amp;bug_status=ASSIGNED&amp;bug_status=REOPENED&amp;emailassigned_to1=1&amp;emailtype1=exact&amp;email1=ppc%40gentoo.org&amp;emailassigned_to2=1&amp;emailreporter2=1&amp;emailqa_contact2=1&amp;emailcc2=1&amp;emailtype2=substring&amp;email2=&amp;bugidtype=include&amp;bug_id=&amp;votes=&amp;changedin=&amp;chfieldfrom=&amp;chfieldto=Now&amp;chfieldvalue=&amp;cmdtype=doit&amp;order=Reuse+same+sort+as+last+time&amp;field0-0-0=noop&amp;type0-0-0=noop&amp;value0-0-0=">bugs</uri>. There are always 
	packages that need to be tested, bugs waiting to be found and fixed 
	and enhancements waiting for someone to code them. Feel free to 
	ask the PPC development team on IRC what <e>you</e> can help us with!
	</p>

        <p>for more information on how the PPC team recruits please read our
	<uri link="recruitment.xml">recruitment</uri> page.
        </p>

      </body>
    </section>
  </extrachapter>

<herd name="ppc"/>
<herd name="ppc64"/>

</project>

=== ulm/gentoo-historical/xml/htdocs/proj/en/pr/events/clt2008-germany/index.xml
<?xml version='1.0' encoding="UTF-8"?>
<!-- $Header: /var/cvsroot/gentoo/xml/htdocs/proj/en/pr/events/clt2008-germany/index.xml,v 1.1 2007/12/09 21:32:16 dertobi123 Exp $ -->
<?xml-stylesheet href="/xsl/project.xsl" type="text/xsl"?>
<?xml-stylesheet href="/xsl/guide.xsl" type="text/xsl"?>
<!DOCTYPE project SYSTEM "/dtd/project.dtd">

<project>
  <name>clt2008-germany</name>
  <longname>Chemnitzer Linuxtage 2008</longname>
  <date>2007-12-09</date>
  <author title="Contact">
    <mail link="dertobi123@gentoo.org">Tobias Scherbaum</mail>
  </author>

  <description>
  This subproject is a place to hold informations on organizing the Gentoo booth
  at the Chemnitzer Linuxtage 2008.
  </description>

  <longdescription>
  <p>
  Gentoo will be present at the Chemnitzer Linuxtage 2008 for the fifth
  time. The event takes place on 1th and 2nd March 2008. Deadline to submit
  talks and projects is January 3, 2008. Our attendance is not confirmed
  yet.
  </p>
  </longdescription>

  <goals>
  <ul>
    <li>Poster</li>
    <li>Flyer</li>
    <li>probably CDs/DVDs</li>
	<li>maybe an event-box</li>
  </ul>
  </goals>

  <extrachapter>
    <title>Preparing the event</title>
    <section>
      <title>People</title>
      <body>
        <p>This is the list of people related to this event:</p>
          <table>
            <tr>
              <th>Name</th>
              <th>Title</th>
              <th>Function on the booth</th>
              <th>Date of arrival</th>
              <th>Date of departure</th>
              <th>City coming from</th>
              <th>Coming using</th>
              <th>Sleeping in</th>
              <th>Email</th>
              <th>Phone</th>
            </tr>
            <tr>
              <ti>Tobias Scherbaum</ti>
              <ti>Gentoo Developer</ti>
              <ti>Organizational contact, booth staff</ti>
              <ti>29th February late evening via LEJ</ti>
              <ti>4th March evening via LEJ</ti>
              <ti>Oberhausen, Germany</ti>
              <ti>plane</ti>
              <ti> ?? </ti>
              <ti>dertobi123@gentoo.org</ti>
              <ti>+49 172 7307110</ti>
            </tr>
            <tr>
              <ti>Robert Buchholz</ti>
              <ti>Gentoo Developer</ti>
              <ti>booth staff</ti>
              <ti></ti>
              <ti></ti>
              <ti>Berlin, Germany</ti>
              <ti> ?? </ti>
              <ti> ?? </ti> 
              <ti>rbu@gentoo.org</ti>
              <ti> ?? </ti>
            </tr>
            <tr>
              <ti>Jan Seidel</ti>
              <ti>former Gentoo Developer</ti>
              <ti>booth staff</ti>
              <ti></ti>
              <ti></ti>
              <ti>Altenburg, Germany</ti>
              <ti> ?? </ti>
              <ti> ?? </ti> 
              <ti></ti>
              <ti> ?? </ti>
            </tr>
            <tr>
              <ti>Jens Bl√§sche</ti>
              <ti>Gentoo User</ti>
              <ti>booth staff</ti>
              <ti></ti>
              <ti></ti>
              <ti> ?? </ti>
              <ti> ?? </ti>
              <ti> ?? </ti> 
              <ti> ?? </ti>
            </tr>


          </table>
      </body>
    </section>
  </extrachapter>
</project>
